#!/bin/sh -ef

. "$(dirname "$0")/config"

./prepare-javascript

mkdir -p "$TEST_OUT_DIR/javascript"
NODE_PRESERVE_SYMLINKS=1 mocha -R xunit \
	--package spec/javascript/package.json \
	spec/javascript/spec >"$TEST_OUT_DIR/javascript/test-output-javascript.xml" || :

./kst-adoption-report javascript
aggregate/convert_to_json javascript "$TEST_OUT_DIR/javascript" "$TEST_OUT_DIR/javascript/ci.json"
