// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('InstanceStdArray', () => {
  it('parses test properly', async () => {
    const { InstanceStdArray } = await import('../compiled/testformats/InstanceStdArray.js');
    const io = new KaitaiStream(fs.readFileSync('src/instance_std_array.bin'));
    const r = new InstanceStdArray(io);
    assert.strictEqual(r.ofs, 16);
    assert.strictEqual(r.qtyEntries, 3);
    assert.strictEqual(r.entrySize, 4);
    assert.strictEqual(r.entries.length, 3);
    assert.deepStrictEqual(r.entries[0], new Uint8Array([17, 17, 17, 17]));
    assert.deepStrictEqual(r.entries[1], new Uint8Array([34, 34, 34, 34]));
    assert.deepStrictEqual(r.entries[2], new Uint8Array([51, 51, 51, 51]));
  });
});
