// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchManualEnumInvalidElse', () => {
  it('parses test properly', async () => {
    const { SwitchManualEnumInvalidElse } = await import('../compiled/SwitchManualEnumInvalidElse.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new SwitchManualEnumInvalidElse(io);
    assert.strictEqual(r.opcodes.length, 2);
    assert.strictEqual(r.opcodes[0].code, 255);
    assert.strictEqual(r.opcodes[0].body.value, 123);
    assert.strictEqual(r.opcodes[1].code, 1);
    assert.strictEqual(r.opcodes[1].body.value, 123);
  });
});
