// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('Docstrings', () => {
  it('parses test properly', async () => {
    const { Docstrings } = await import('#testformats/Docstrings.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new Docstrings(io);
  });
});
