// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('DefaultEndianExprInherited', () => {
  it('parses test properly', async () => {
    const { DefaultEndianExprInherited } = await import('#testformats/DefaultEndianExprInherited.js');
    const io = new KaitaiStream(fs.readFileSync('src/endian_expr.bin'));
    const r = new DefaultEndianExprInherited(io);
    assert.deepStrictEqual(r.docs[0].indicator, new Uint8Array([73, 73]));
    assert.strictEqual(r.docs[0].main.insides.someInt, 66);
    assert.strictEqual(r.docs[0].main.insides.more.someInt1, 16896);
    assert.strictEqual(r.docs[0].main.insides.more.someInt2, 66);
    assert.strictEqual(r.docs[0].main.insides.more.someInst, 66);
    assert.deepStrictEqual(r.docs[1].indicator, new Uint8Array([77, 77]));
    assert.strictEqual(r.docs[1].main.insides.someInt, 66);
    assert.strictEqual(r.docs[1].main.insides.more.someInt1, 66);
    assert.strictEqual(r.docs[1].main.insides.more.someInt2, 16896);
    assert.strictEqual(r.docs[1].main.insides.more.someInst, 1107296256);
    assert.deepStrictEqual(r.docs[2].indicator, new Uint8Array([88, 88]));
    assert.strictEqual(r.docs[2].main.insides.someInt, 66);
    assert.strictEqual(r.docs[2].main.insides.more.someInt1, 66);
    assert.strictEqual(r.docs[2].main.insides.more.someInt2, 16896);
    assert.strictEqual(r.docs[2].main.insides.more.someInst, 1107296256);
  });
});
