// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('NestedSameName2', () => {
  it('parses test properly', async () => {
    const { NestedSameName2 } = await import('../compiled/testformats/NestedSameName2.js');
    const io = new KaitaiStream(fs.readFileSync('src/nested_same_name2.bin'));
    const r = new NestedSameName2(io);
    assert.strictEqual(r.version, 66);
    assert.strictEqual(r.mainData.mainSize, 2);
    assert.deepStrictEqual(r.mainData.foo.data1, new Uint8Array([17, 17, 17, 17]));
    assert.strictEqual(r.dummy.dummySize, 3);
    assert.deepStrictEqual(r.dummy.foo.data2, new Uint8Array([34, 34, 34, 34, 34, 34]));
  });
});
