// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsPassArrayInt', () => {
  it('parses test properly', async () => {
    const { ParamsPassArrayInt } = await import('../compiled/testformats/ParamsPassArrayInt.js');
    const io = new KaitaiStream(fs.readFileSync('src/position_to_end.bin'));
    const r = new ParamsPassArrayInt(io);
    assert.strictEqual(r.passInts.nums.length, 3);
    assert.strictEqual(r.passInts.nums[0], 513);
    assert.strictEqual(r.passInts.nums[1], 1027);
    assert.strictEqual(r.passInts.nums[2], 1541);
    assert.strictEqual(r.passIntsCalc.nums.length, 2);
    assert.strictEqual(r.passIntsCalc.nums[0], 27643);
    assert.strictEqual(r.passIntsCalc.nums[1], 7);
  });
});
