// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StructPadTerm', () => {
  it('parses test properly', async () => {
    const { StructPadTerm } = await import('#testformats/StructPadTerm.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term.bin'));
    const r = new StructPadTerm(io);
    assert.deepStrictEqual(r.strPad.value, new Uint8Array([115, 116, 114, 49]));
    assert.deepStrictEqual(r.strTerm.value, new Uint8Array([115, 116, 114, 50, 102, 111, 111]));
    assert.deepStrictEqual(r.strTermAndPad.value, new Uint8Array([115, 116, 114, 43, 43, 43, 51, 98, 97, 114, 43, 43, 43]));
    assert.deepStrictEqual(r.strTermInclude.value, new Uint8Array([115, 116, 114, 52, 98, 97, 122, 64]));
  });
});
