// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailMaxInt', () => {
  it('parses test properly', async () => {
    const { ValidFailMaxInt } = await import('../compiled/ValidFailMaxInt.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    assert.ok(KaitaiStream.ValidationGreaterThanError);
    assert.throws(() => new ValidFailMaxInt(io), KaitaiStream.ValidationGreaterThanError);
  });
});
