// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsShiftByB64Le', () => {
  it('parses test properly', async () => {
    const { BitsShiftByB64Le } = await import('../compiled/BitsShiftByB64Le.js');
    const io = new KaitaiStream(fs.readFileSync('src/bits_shift_by_b64_le.bin'));
    const r = new BitsShiftByB64Le(io);
    assert.strictEqual(r.a, 18446744073709551615);
    assert.strictEqual(r.b, 0);
  });
});
