// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StructPadTermEqual', () => {
  it('parses test properly', async () => {
    const { StructPadTermEqual } = await import('../compiled/StructPadTermEqual.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term.bin'));
    const r = new StructPadTermEqual(io);
    assert.deepStrictEqual(r.s1.value, new Uint8Array([115, 116, 114, 49]));
    assert.deepStrictEqual(r.s2.value, new Uint8Array([115, 116, 114, 50, 102, 111, 111, 64]));
    assert.deepStrictEqual(r.s3.value, new Uint8Array([115, 116, 114]));
    assert.deepStrictEqual(r.s4.value, new Uint8Array([115, 116, 114, 52, 98, 97, 122, 64, 46]));
  });
});
