// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprEnum', () => {
  it('parses test properly', async () => {
    const { ExprEnum } = await import('../compiled/ExprEnum.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new ExprEnum(io);
    assert.strictEqual(r.constDog, ExprEnum.Animal.DOG);
    assert.strictEqual(r.derivedBoom, ExprEnum.Animal.BOOM);
    assert.strictEqual(r.derivedDog, ExprEnum.Animal.DOG);
  });
});
