// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumInvalid', () => {
  it('parses test properly', async () => {
    const { EnumInvalid } = await import('../compiled/testformats/EnumInvalid.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new EnumInvalid(io);
    assert.strictEqual(r.pet1, EnumInvalid.Animal.DOG);
    assert.strictEqual(r.pet2, 111);
  });
});
