// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprBits', () => {
  it('parses test properly', async () => {
    const { ExprBits } = await import('#testformats/ExprBits.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_opcodes.bin'));
    const r = new ExprBits(io);
    assert.strictEqual(r.a, 2);
    assert.strictEqual(r.enumSeq, ExprBits.Items.FOO);
    assert.deepStrictEqual(r.byteSize, new Uint8Array([102, 111]));
    assert.strictEqual(r.repeatExpr.length, 2);
    assert.strictEqual(r.repeatExpr[0], 111);
    assert.strictEqual(r.repeatExpr[1], 98);
    assert.strictEqual(r.switchOnType, 97);
    assert.strictEqual(r.switchOnEndian.foo, 29184);
    assert.strictEqual(r.enumInst, ExprBits.Items.BAR);
    assert.strictEqual(r.instPos, 111);
  });
});
