// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('CombineEnum', () => {
  it('parses test properly', async () => {
    const { CombineEnum } = await import('#testformats/CombineEnum.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new CombineEnum(io);
    assert.strictEqual(r.enumU4, CombineEnum.Animal.PIG);
    assert.strictEqual(r.enumU2, CombineEnum.Animal.HORSE);
    assert.strictEqual(r.enumU4U2, CombineEnum.Animal.HORSE);
  });
});
