// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ImportsAbsAbs', () => {
  it('parses test properly', async () => {
    const { ImportsAbsAbs } = await import('../compiled/testformats/ImportsAbsAbs.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ImportsAbsAbs(io);
    assert.strictEqual(r.one, 80);
    assert.strictEqual(r.two.one, 65);
    assert.strictEqual(r.two.two.one, 67);
  });
});
