// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StrPadTermEqual', () => {
  it('parses test properly', async () => {
    const { StrPadTermEqual } = await import('../compiled/StrPadTermEqual.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term.bin'));
    const r = new StrPadTermEqual(io);
    assert.strictEqual(r.s1, "str1");
    assert.strictEqual(r.s2, "str2foo@");
    assert.strictEqual(r.s3, "str");
    assert.strictEqual(r.s4, "str4baz@.");
  });
});
