// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('HelloWorld', () => {
  it('parses test properly', async () => {
    const { HelloWorld } = await import('../compiled/testformats/HelloWorld.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new HelloWorld(io);
    assert.strictEqual(r.one, 80);
  });
});
