// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprOpsParens', () => {
  it('parses test properly', async () => {
    const { ExprOpsParens } = await import('../compiled/ExprOpsParens.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new ExprOpsParens(io);
    assert.strictEqual(r.iSumToStr, "29");
    assert.strictEqual(r.fSumToInt, 9);
    assert.strictEqual(r.strConcatLen, 10);
    assert.strictEqual(r.strConcatRev, "9876543210");
    assert.strictEqual(r.strConcatSubstr2To7, "23456");
    assert.strictEqual(r.strConcatToI, 123456789);
    assert.strictEqual(r.boolEq, 0);
    assert.strictEqual(r.boolAnd, 0);
    assert.strictEqual(r.boolOr, 1);
  });
});
