// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('TermStruct3', () => {
  it('parses test properly', async () => {
    const { TermStruct3 } = await import('../compiled/testformats/TermStruct3.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TermStruct3(io);
    assert.deepStrictEqual(r.s1.value, new Uint8Array([102, 111, 111]));
    assert.deepStrictEqual(r.s2.value, new Uint8Array([124, 98, 97, 114, 124, 98, 97, 122]));
    assert.deepStrictEqual(r.s3.value, new Uint8Array([]));
  });
});
