// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NavParentSwitchCast', () => {
  it('parses test properly', async () => {
    const { NavParentSwitchCast } = await import('#testformats/NavParentSwitchCast.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_integers.bin'));
    const r = new NavParentSwitchCast(io);
    assert.strictEqual(r.main.bufType, 1);
    assert.strictEqual(r.main.flag, 7);
    assert.strictEqual(r.main.buf.branch.flag, 7);
  });
});
