// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('DefaultEndianMod', () => {
  it('parses test properly', async () => {
    const { DefaultEndianMod } = await import('../compiled/DefaultEndianMod.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new DefaultEndianMod(io);
    assert.strictEqual(r.main.one, 1262698832);
    assert.strictEqual(r.main.nest.two, -52947);
    assert.strictEqual(r.main.nestBe.two, 1346454347);
  });
});
