// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('CombineStr', () => {
  it('parses test properly', async () => {
    const { CombineStr } = await import('../compiled/CombineStr.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new CombineStr(io);
    assert.strictEqual(r.strTerm, "foo");
    assert.strictEqual(r.strLimit, "bar|");
    assert.strictEqual(r.strEos, "baz@");
    assert.strictEqual(r.strCalc, "bar");
    assert.strictEqual(r.strCalcBytes, "baz");
    assert.strictEqual(r.termOrLimit, "foo");
    assert.strictEqual(r.termOrEos, "baz@");
    assert.strictEqual(r.termOrCalc, "foo");
    assert.strictEqual(r.termOrCalcBytes, "baz");
    assert.strictEqual(r.limitOrEos, "bar|");
    assert.strictEqual(r.limitOrCalc, "bar");
    assert.strictEqual(r.limitOrCalcBytes, "bar|");
    assert.strictEqual(r.eosOrCalc, "bar");
    assert.strictEqual(r.eosOrCalcBytes, "baz@");
    assert.strictEqual(r.calcOrCalcBytes, "baz");
  });
});
