// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('StrEncodings', () => {
  it('parses test properly', async () => {
    const { StrEncodings } = await import('../compiled/testformats/StrEncodings.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_encodings.bin'));
    const r = new StrEncodings(io);
    assert.strictEqual(r.str1, "Some ASCII");
    assert.strictEqual(r.str2, "\u3053\u3093\u306b\u3061\u306f");
    assert.strictEqual(r.str3, "\u3053\u3093\u306b\u3061\u306f");
    assert.strictEqual(r.str4, "\u2591\u2592\u2593");
  });
});
