// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchManualStr', () => {
  it('parses test properly', async () => {
    const { SwitchManualStr } = await import('../compiled/SwitchManualStr.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_opcodes.bin'));
    const r = new SwitchManualStr(io);
    assert.strictEqual(r.opcodes.length, 4);
    assert.strictEqual(r.opcodes[0].code, "S");
    assert.strictEqual(r.opcodes[0].body.value, "foobar");
    assert.strictEqual(r.opcodes[1].code, "I");
    assert.strictEqual(r.opcodes[1].body.value, 66);
    assert.strictEqual(r.opcodes[2].code, "I");
    assert.strictEqual(r.opcodes[2].body.value, 55);
    assert.strictEqual(r.opcodes[3].code, "S");
    assert.strictEqual(r.opcodes[3].body.value, "");
  });
});
