// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NavRootRecursive', () => {
  it('parses test properly', async () => {
    const { NavRootRecursive } = await import('#testformats/NavRootRecursive.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new NavRootRecursive(io);
    assert.strictEqual(r.value, 255);
    assert.strictEqual(r.next.value, 1);
    assert.strictEqual(r.next.rootValue, 255);
    assert.strictEqual(r.next.next, undefined);
  });
});
