// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('CastNested', () => {
  it('parses test properly', async () => {
    const { CastNested } = await import('#testformats/CastNested.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_opcodes.bin'));
    const r = new CastNested(io);
    assert.strictEqual(r.opcodes0Str.value, "foobar");
    assert.strictEqual(r.opcodes0StrValue, "foobar");
    assert.strictEqual(r.opcodes1Int.value, 66);
    assert.strictEqual(r.opcodes1IntValue, 66);
  });
});
