// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('TermBytes2', () => {
  it('parses test properly', async () => {
    const { TermBytes2 } = await import('#testformats/TermBytes2.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TermBytes2(io);
    assert.deepStrictEqual(r.s1, new Uint8Array([102, 111, 111]));
    assert.deepStrictEqual(r.s2, new Uint8Array([98, 97, 114, 124]));
    assert.deepStrictEqual(r.s3, new Uint8Array([98, 97, 122]));
  });
});
