// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('RecursiveOne', () => {
  it('parses test properly', async () => {
    const { RecursiveOne } = await import('../compiled/testformats/RecursiveOne.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new RecursiveOne(io);
    assert.strictEqual(r.one, 80);
    assert.strictEqual(r.next.one, 65);
    assert.strictEqual(r.next.next.one, 67);
    assert.strictEqual(r.next.next.next.finisher, 11595);
  });
});
