// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('FloatingPoints', () => {
  it('parses test properly', async () => {
    const { FloatingPoints } = await import('#testformats/FloatingPoints.js');
    const io = new KaitaiStream(fs.readFileSync('src/floating_points.bin'));
    const r = new FloatingPoints(io);
    assert(Math.abs(r.singleValue - 0.5) < 1e-6);
    assert(Math.abs(r.singleValueBe - 0.5) < 1e-6);
    assert(Math.abs(r.doubleValue - 0.25) < 1e-6);
    assert(Math.abs(r.doubleValueBe - 0.25) < 1e-6);
    assert(Math.abs(r.approximateValue - 1.2345) < 1e-6);
    assert(Math.abs(r.singleValuePlusInt - 1.5) < 1e-6);
    assert(Math.abs(r.singleValuePlusFloat - 1.0) < 1e-6);
    assert(Math.abs(r.doubleValuePlusFloat - 0.3) < 1e-6);
  });
});
