// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('TermStrzUtf16V4', () => {
  it('parses test properly', async () => {
    const { TermStrzUtf16V4 } = await import('../compiled/testformats/TermStrzUtf16V4.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz_utf16.bin'));
    const r = new TermStrzUtf16V4(io);
    assert.strictEqual(r.s1.value, "a\u0200b");
    assert.strictEqual(r.s2.value, "c\u0200d");
    assert.strictEqual(r.s3.value, "e\u0200f");
  });
});
