// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('NavParentOverride', () => {
  it('parses test properly', async () => {
    const { NavParentOverride } = await import('../compiled/testformats/NavParentOverride.js');
    const io = new KaitaiStream(fs.readFileSync('src/nav_parent_codes.bin'));
    const r = new NavParentOverride(io);
    assert.strictEqual(r.childSize, 3);
    assert.deepStrictEqual(r.child1.data, new Uint8Array([73, 49, 50]));
    assert.deepStrictEqual(r.mediator2.child2.data, new Uint8Array([51, 66, 98]));
  });
});
