// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('BytesPadTermEmpty', () => {
  it('parses test properly', async () => {
    const { BytesPadTermEmpty } = await import('../compiled/testformats/BytesPadTermEmpty.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term_empty.bin'));
    const r = new BytesPadTermEmpty(io);
    assert.deepStrictEqual(r.strPad, new Uint8Array([]));
    assert.deepStrictEqual(r.strTerm, new Uint8Array([]));
    assert.deepStrictEqual(r.strTermAndPad, new Uint8Array([]));
    assert.deepStrictEqual(r.strTermInclude, new Uint8Array([64]));
  });
});
