// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('StrPadTermUtf16', () => {
  it('parses test properly', async () => {
    const { StrPadTermUtf16 } = await import('../compiled/testformats/StrPadTermUtf16.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term_utf16.bin'));
    const r = new StrPadTermUtf16(io);
    assert.strictEqual(r.strTerm, "a\u0200b");
    assert.strictEqual(r.strTermInclude, "c\u0200d\x00");
    assert.strictEqual(r.strTermAndPad, "e\u0200f");
  });
});
