// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumToIInvalid', () => {
  it('parses test properly', async () => {
    const { EnumToIInvalid } = await import('#testformats/EnumToIInvalid.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new EnumToIInvalid(io);
    assert.strictEqual(r.pet1, EnumToIInvalid.Animal.DOG);
    assert.strictEqual(r.pet2, 111);
    assert.strictEqual(r.pet2I, 111);
    assert.strictEqual(r.pet2IToS, "111");
    assert.strictEqual(r.pet2Mod, 32879);
    assert.strictEqual(r.oneLtTwo, true);
    assert.strictEqual(r.pet2EqIntT, true);
    assert.strictEqual(r.pet2EqIntF, false);
  });
});
