// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessToUser', () => {
  it('parses test properly', async () => {
    const { ProcessToUser } = await import('../compiled/testformats/ProcessToUser.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_rotate.bin'));
    const r = new ProcessToUser(io);
    assert.strictEqual(r.buf1.str, "Hello");
  });
});
