// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatNTermStruct', () => {
  it('parses test properly', async () => {
    const { RepeatNTermStruct } = await import('../compiled/testformats/RepeatNTermStruct.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_until_process.bin'));
    const r = new RepeatNTermStruct(io);
    assert.strictEqual(r.records1.length, 2);
    assert.deepStrictEqual(r.records1[0].value, new Uint8Array([232, 186]));
    assert.deepStrictEqual(r.records1[1].value, new Uint8Array([]));
    assert.strictEqual(r.records2.length, 2);
    assert.deepStrictEqual(r.records2[0].value, new Uint8Array([170]));
    assert.deepStrictEqual(r.records2[1].value, new Uint8Array([250, 158, 184, 170]));
    assert.strictEqual(r.records3.length, 2);
    assert.deepStrictEqual(r.records3[0].value, new Uint8Array([170, 170]));
    assert.deepStrictEqual(r.records3[1].value, new Uint8Array([]));
  });
});
