// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprFstring0', () => {
  it('parses test properly', async () => {
    const { ExprFstring0 } = await import('#testformats/ExprFstring0.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new ExprFstring0(io);
    assert.strictEqual(r.seqStr, "foo|b");
    assert.strictEqual(r.seqInt, 97);
    assert.strictEqual(r.empty, "");
    assert.strictEqual(r.literal, "abc");
    assert.strictEqual(r.literalWithEscapes, "abc\n\tt");
    assert.strictEqual(r.headAndIntLiteral, "abc=123");
    assert.strictEqual(r.headAndStrLiteral, "abc=foo");
    assert.strictEqual(r.headAndInt, "abc=97");
    assert.strictEqual(r.headAndStr, "abc=foo|b");
  });
});
