// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsCall', () => {
  it('parses test properly', async () => {
    const { ParamsCall } = await import('../compiled/ParamsCall.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new ParamsCall(io);
    assert.strictEqual(r.buf1.body, "foo|b");
    assert.strictEqual(r.buf2.body, "ar|ba");
    assert.strictEqual(r.buf2.trailer, 122);
  });
});
