// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('DefaultBigEndian', () => {
  it('parses test properly', async () => {
    const { DefaultBigEndian } = await import('../compiled/testformats/DefaultBigEndian.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new DefaultBigEndian(io);
    assert.strictEqual(r.one, 117440512);
  });
});
