// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ImportsAbs', () => {
  it('parses test properly', async () => {
    const { ImportsAbs } = await import('../compiled/testformats/ImportsAbs.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ImportsAbs(io);
    assert.strictEqual(r.len.value, 80);
    assert.strictEqual(r.body.length, 80);
  });
});
