// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprSizeofType1', () => {
  it('parses test properly', async () => {
    const { ExprSizeofType1 } = await import('../compiled/ExprSizeofType1.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ExprSizeofType1(io);
    assert.strictEqual(r.sizeofBlock, ((1 + 4) + 2) + 4);
    assert.strictEqual(r.sizeofSubblock, 4);
  });
});
