// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('InstanceIoUser', () => {
  it('parses test properly', async () => {
    const { InstanceIoUser } = await import('../compiled/testformats/InstanceIoUser.js');
    const io = new KaitaiStream(fs.readFileSync('src/instance_io.bin'));
    const r = new InstanceIoUser(io);
    assert.strictEqual(r.qtyEntries, 3);
    assert.strictEqual(r.entries[0].name, "the");
    assert.strictEqual(r.entries[1].name, "rainy");
    assert.strictEqual(r.entries[2].name, "day it is");
  });
});
