// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessRepeatUsertypeDynargCustom', () => {
  it('parses test properly', async () => {
    const { ProcessRepeatUsertypeDynargCustom } = await import('../compiled/ProcessRepeatUsertypeDynargCustom.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_rotate.bin'));
    const r = new ProcessRepeatUsertypeDynargCustom(io);
    assert.strictEqual(r.blocks[0].a, 2290657028);
    assert.strictEqual(r.blocks[1].a, 2057999057);
    assert.strictEqual(r.blocksB.dummy, 1);
    assert.strictEqual(r.blocksB.blocks0B, 232);
    assert.strictEqual(r.blocksB.blocks1B, 58);
  });
});
