// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('NavParentFalse2', () => {
  it('parses test properly', async () => {
    const { NavParentFalse2 } = await import('../compiled/testformats/NavParentFalse2.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new NavParentFalse2(io);
    assert.strictEqual(r.parentless.foo, 80);
  });
});
