// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ImportsCircularA', () => {
  it('parses test properly', async () => {
    const { ImportsCircularA } = await import('../compiled/testformats/ImportsCircularA.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ImportsCircularA(io);
    assert.strictEqual(r.code, 80);
    assert.strictEqual(r.two.initial, 65);
    assert.strictEqual(r.two.backRef.code, 67);
    assert.strictEqual(r.two.backRef.two.initial, 75);
    assert.strictEqual(r.two.backRef.two.backRef, undefined);
  });
});
