// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprBytesCmp', () => {
  it('parses test properly', async () => {
    const { ExprBytesCmp } = await import('#testformats/ExprBytesCmp.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ExprBytesCmp(io);
    assert.deepStrictEqual(r.one, new Uint8Array([80]));
    assert.deepStrictEqual(r.two, new Uint8Array([65, 67, 75]));
    assert.strictEqual(r.isEq, true);
    assert.strictEqual(r.isNe, false);
    assert.strictEqual(r.isLt, true);
    assert.strictEqual(r.isGt, false);
    assert.strictEqual(r.isLe, true);
    assert.strictEqual(r.isGe, false);
    assert.strictEqual(r.isLt2, false);
    assert.strictEqual(r.isGt2, true);
  });
});
