// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsUnalignedB32Be', () => {
  it('parses test properly', async () => {
    const { BitsUnalignedB32Be } = await import('../compiled/testformats/BitsUnalignedB32Be.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new BitsUnalignedB32Be(io);
    assert.strictEqual(r.a, true);
    assert.strictEqual(r.b, 3648472617);
    assert.strictEqual(r.c, 10);
  });
});
