// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessCustom', () => {
  it('parses test properly', async () => {
    const { ProcessCustom } = await import('../compiled/ProcessCustom.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_rotate.bin'));
    const r = new ProcessCustom(io);
    assert.deepStrictEqual(r.buf1, new Uint8Array([16, 179, 148, 148, 244]));
    assert.deepStrictEqual(r.buf2, new Uint8Array([95, 186, 123, 147, 99, 35, 95]));
    assert.deepStrictEqual(r.buf3, new Uint8Array([41, 51, 177, 56, 177]));
  });
});
