// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsUnalignedB32Le', () => {
  it('parses test properly', async () => {
    const { BitsUnalignedB32Le } = await import('#testformats/BitsUnalignedB32Le.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new BitsUnalignedB32Le(io);
    assert.strictEqual(r.a, false);
    assert.strictEqual(r.b, 173137398);
    assert.strictEqual(r.c, 69);
  });
});
