// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessBytesPadTerm', () => {
  it('parses test properly', async () => {
    const { ProcessBytesPadTerm } = await import('../compiled/testformats/ProcessBytesPadTerm.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term.bin'));
    const r = new ProcessBytesPadTerm(io);
    assert.deepStrictEqual(r.strPad, new Uint8Array([102, 97, 103, 36]));
    assert.deepStrictEqual(r.strTerm, new Uint8Array([102, 97, 103, 39, 115, 122, 122]));
    assert.deepStrictEqual(r.strTermAndPad, new Uint8Array([102, 97, 103, 62, 62, 62, 38, 119, 116, 103, 62, 62, 62]));
    assert.deepStrictEqual(r.strTermInclude, new Uint8Array([102, 97, 103, 33, 119, 116, 111, 85]));
  });
});
