// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsSeqEndianCombo', () => {
  it('parses test properly', async () => {
    const { BitsSeqEndianCombo } = await import('../compiled/testformats/BitsSeqEndianCombo.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new BitsSeqEndianCombo(io);
    assert.strictEqual(r.be1, 59);
    assert.strictEqual(r.be2, 187);
    assert.strictEqual(r.le3, 163);
    assert.strictEqual(r.be4, 20);
    assert.strictEqual(r.le5, 10);
    assert.strictEqual(r.le6, 36);
    assert.strictEqual(r.le7, 26);
    assert.strictEqual(r.be8, true);
  });
});
