// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessXor4Value', () => {
  it('parses test properly', async () => {
    const { ProcessXor4Value } = await import('../compiled/ProcessXor4Value.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new ProcessXor4Value(io);
    assert.deepStrictEqual(r.key, new Uint8Array([236, 187, 163, 20]));
    assert.deepStrictEqual(r.buf, new Uint8Array([102, 111, 111, 32, 98, 97, 114]));
  });
});
