// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('TermStrz4', () => {
  it('parses test properly', async () => {
    const { TermStrz4 } = await import('../compiled/testformats/TermStrz4.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TermStrz4(io);
    assert.strictEqual(r.s1.value, "foo");
    assert.strictEqual(r.s2.value, "bar");
    assert.strictEqual(r.s3.value, "baz");
  });
});
