// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumOfValueInst', () => {
  it('parses test properly', async () => {
    const { EnumOfValueInst } = await import('../compiled/EnumOfValueInst.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new EnumOfValueInst(io);
    assert.strictEqual(r.pet1, EnumOfValueInst.Animal.CAT);
    assert.strictEqual(r.pet2, EnumOfValueInst.Animal.CHICKEN);
    assert.strictEqual(r.pet3, EnumOfValueInst.Animal.DOG);
    assert.strictEqual(r.pet4, EnumOfValueInst.Animal.DOG);
  });
});
