// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsPassArrayStruct', () => {
  it('parses test properly', async () => {
    const { ParamsPassArrayStruct } = await import('../compiled/testformats/ParamsPassArrayStruct.js');
    const io = new KaitaiStream(fs.readFileSync('src/position_to_end.bin'));
    const r = new ParamsPassArrayStruct(io);
    assert.strictEqual(r.passStructs.structs.length, 2);
    assert.strictEqual(r.passStructs.structs[0].f, 1);
    assert.strictEqual(r.passStructs.structs[1].b, 2);
  });
});
