// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('PositionToEnd', () => {
  it('parses test properly', async () => {
    const { PositionToEnd } = await import('#testformats/PositionToEnd.js');
    const io = new KaitaiStream(fs.readFileSync('src/position_to_end.bin'));
    const r = new PositionToEnd(io);
    assert.strictEqual(r.index.foo, 66);
    assert.strictEqual(r.index.bar, 4660);
  });
});
