// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('UserType', () => {
  it('parses test properly', async () => {
    const { UserType } = await import('#testformats/UserType.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_until_s4.bin'));
    const r = new UserType(io);
    assert.strictEqual(r.one.width, 66);
    assert.strictEqual(r.one.height, 4919);
  });
});
