// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchBytearray', () => {
  it('parses test properly', async () => {
    const { SwitchBytearray } = await import('../compiled/testformats/SwitchBytearray.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_opcodes.bin'));
    const r = new SwitchBytearray(io);
    assert.strictEqual(r.opcodes.length, 4);
    assert.deepStrictEqual(r.opcodes[0].code, new Uint8Array([83]));
    assert.strictEqual(r.opcodes[0].body.value, "foobar");
    assert.deepStrictEqual(r.opcodes[1].code, new Uint8Array([73]));
    assert.strictEqual(r.opcodes[1].body.value, 66);
    assert.deepStrictEqual(r.opcodes[2].code, new Uint8Array([73]));
    assert.strictEqual(r.opcodes[2].body.value, 55);
    assert.deepStrictEqual(r.opcodes[3].code, new Uint8Array([83]));
    assert.strictEqual(r.opcodes[3].body.value, "");
  });
});
