// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('BcdUserTypeBe', () => {
  it('parses test properly', async () => {
    const { BcdUserTypeBe } = await import('../compiled/BcdUserTypeBe.js');
    const io = new KaitaiStream(fs.readFileSync('src/bcd_user_type_be.bin'));
    const r = new BcdUserTypeBe(io);
    assert.strictEqual(r.ltr.asInt, 12345678);
    assert.strictEqual(r.ltr.asStr, "12345678");
    assert.strictEqual(r.rtl.asInt, 87654321);
    assert.strictEqual(r.rtl.asStr, "87654321");
    assert.strictEqual(r.leadingZeroLtr.asInt, 123456);
    assert.strictEqual(r.leadingZeroLtr.asStr, "00123456");
  });
});
