// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailContentsInst', () => {
  it('parses test properly', async () => {
    const { ValidFailContentsInst } = await import('../compiled/testformats/ValidFailContentsInst.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    assert.ok(KaitaiStream.ValidationNotEqualError);
    assert.throws(() => new ValidFailContentsInst(io), KaitaiStream.ValidationNotEqualError);
  });
});
