// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatUntilSized', () => {
  it('parses test properly', async () => {
    const { RepeatUntilSized } = await import('../compiled/testformats/RepeatUntilSized.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_until_process.bin'));
    const r = new RepeatUntilSized(io);
    assert.strictEqual(r.records.length, 3);
    assert.strictEqual(r.records[0].marker, 232);
    assert.strictEqual(r.records[0].body, 2863311546);
    assert.strictEqual(r.records[1].marker, 250);
    assert.strictEqual(r.records[1].body, 2863315102);
    assert.strictEqual(r.records[2].marker, 170);
    assert.strictEqual(r.records[2].body, 1431655765);
  });
});
