// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprIoPos', () => {
  it('parses test properly', async () => {
    const { ExprIoPos } = await import('../compiled/testformats/ExprIoPos.js');
    const io = new KaitaiStream(fs.readFileSync('src/expr_io_pos.bin'));
    const r = new ExprIoPos(io);
    assert.strictEqual(r.substream1.myStr, "CURIOSITY");
    assert.deepStrictEqual(r.substream1.body, new Uint8Array([17, 34, 51, 68]));
    assert.strictEqual(r.substream1.number, 66);
    assert.strictEqual(r.substream2.myStr, "KILLED");
    assert.deepStrictEqual(r.substream2.body, new Uint8Array([97, 32, 99, 97, 116]));
    assert.strictEqual(r.substream2.number, 103);
  });
});
