// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('InstanceIoUserEarlier', () => {
  it('parses test properly', async () => {
    const { InstanceIoUserEarlier } = await import('../compiled/InstanceIoUserEarlier.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_opcodes2.bin'));
    const r = new InstanceIoUserEarlier(io);
    assert.strictEqual(r.sizedA.content, 83);
    assert.strictEqual(r.intoA.inst.content, 102);
    assert.strictEqual(r.aMid, 28527);
    assert.strictEqual(r.intoA.inst.last, 0);
    assert.strictEqual(r.sizedA.last, 88);
    assert.strictEqual(r.sizedB.content, 66);
    assert.strictEqual(r.intoB.inst.content, 0);
    assert.strictEqual(r.bMid, 0);
    assert.strictEqual(r.intoB.inst.last, 89);
    assert.strictEqual(r.sizedB.last, 254);
    assert.strictEqual(r.intoB.indicator, 202);
    assert.strictEqual(r.intoASkipped.indicator, 0);
    assert.strictEqual(r.intoASkipped.inst._io.size, 0);
    assert.strictEqual(r.intoA.indicator, 0);
    assert.strictEqual(r.intoA.bar, 73);
    assert.strictEqual(r.lastAccessor.v, 7);
  });
});
