// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprIfIntEq', () => {
  it('parses test properly', async () => {
    const { ExprIfIntEq } = await import('../compiled/testformats/ExprIfIntEq.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_coerce_switch.bin'));
    const r = new ExprIfIntEq(io);
    assert.strictEqual(r.seqEqLit, true);
    assert.strictEqual(r.seqEqCalc, true);
    assert.strictEqual(r.seqEqCalcIf, true);
    assert.strictEqual(r.seqEqSeqIf, true);
    assert.strictEqual(r.calcEqLit, true);
    assert.strictEqual(r.calcEqCalcIf, true);
    assert.strictEqual(r.calcEqSeqIf, true);
    assert.strictEqual(r.calcIfEqLit, true);
    assert.strictEqual(r.calcIfEqSeqIf, true);
    assert.strictEqual(r.seqIfEqLit, true);
  });
});
