// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NestedTypes', () => {
  it('parses test properly', async () => {
    const { NestedTypes } = await import('#testformats/NestedTypes.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new NestedTypes(io);
    assert.strictEqual(r.one.typedAtRoot.valueB, 80);
    assert.strictEqual(r.one.typedHere.valueC, 65);
    assert.strictEqual(r.two.valueB, 67);
  });
});
