// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('IfInstances', () => {
  it('parses test properly', async () => {
    const { IfInstances } = await import('../compiled/testformats/IfInstances.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new IfInstances(io);
    assert.strictEqual(r.neverHappens, undefined);
  });
});
