// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('NavParentRecursive', () => {
  it('parses test properly', async () => {
    const { NavParentRecursive } = await import('../compiled/testformats/NavParentRecursive.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new NavParentRecursive(io);
    assert.strictEqual(r.value, 255);
    assert.strictEqual(r.next.value, 1);
    assert.strictEqual(r.next.parentValue, 255);
    assert.strictEqual(r.next.next, undefined);
  });
});
