// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumNegative', () => {
  it('parses test properly', async () => {
    const { EnumNegative } = await import('#testformats/EnumNegative.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new EnumNegative(io);
    assert.strictEqual(r.f1, EnumNegative.Constants.NEGATIVE_ONE);
    assert.strictEqual(r.f2, EnumNegative.Constants.POSITIVE_ONE);
  });
});
