// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('StrEosPadTermEqual', () => {
  it('parses test properly', async () => {
    const { StrEosPadTermEqual } = await import('../compiled/testformats/StrEosPadTermEqual.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term.bin'));
    const r = new StrEosPadTermEqual(io);
    assert.strictEqual(r.s1.value, "str1");
    assert.strictEqual(r.s2.value, "str2foo@");
    assert.strictEqual(r.s3.value, "str");
    assert.strictEqual(r.s4.value, "str4baz@.");
  });
});
