// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatNStrzDouble', () => {
  it('parses test properly', async () => {
    const { RepeatNStrzDouble } = await import('#testformats/RepeatNStrzDouble.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_n_strz.bin'));
    const r = new RepeatNStrzDouble(io);
    assert.strictEqual(r.qty, 2);
    assert.deepStrictEqual(r.lines1, ["foo"]);
    assert.deepStrictEqual(r.lines2, ["bar"]);
  });
});
