// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NestedSameName', () => {
  it('parses test properly', async () => {
    const { NestedSameName } = await import('#testformats/NestedSameName.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_n_struct.bin'));
    const r = new NestedSameName(io);
    assert.strictEqual(r.mainData.mainSize, 2);
    assert.deepStrictEqual(r.mainData.foo.data, new Uint8Array([16, 0, 0, 0]));
  });
});
