// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('EofExceptionU4', () => {
  it('parses test properly', async () => {
    const { EofExceptionU4 } = await import('../compiled/testformats/EofExceptionU4.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    assert.ok(KaitaiStream.EOFError);
    assert.throws(() => new EofExceptionU4(io), KaitaiStream.EOFError);
  });
});
