// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatEosBitsB4', () => {
  it('parses test properly', async () => {
    const { RepeatEosBitsB4 } = await import('#testformats/RepeatEosBitsB4.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new RepeatEosBitsB4(io);
    assert.strictEqual(r.nibbles.length, 4);
    assert.strictEqual(r.nibbles[0], 15);
    assert.strictEqual(r.nibbles[1], 15);
    assert.strictEqual(r.nibbles[2], 0);
    assert.strictEqual(r.nibbles[3], 1);
  });
});
