// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailRangeInt', () => {
  it('parses test properly', async () => {
    const { ValidFailRangeInt } = await import('#testformats/ValidFailRangeInt.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    assert.ok(KaitaiStream.ValidationGreaterThanError);
    assert.throws(() => new ValidFailRangeInt(io), KaitaiStream.ValidationGreaterThanError);
  });
});
