// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumImportSeq', () => {
  it('parses test properly', async () => {
    const { EnumImportSeq } = await import('../compiled/EnumImportSeq.js');
    const { Enum0 } = await import('../compiled/Enum0.js');
    const { EnumDeep } = await import('../compiled/EnumDeep.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new EnumImportSeq(io);
    assert.strictEqual(r.pet1, Enum0.Animal.CAT);
    assert.strictEqual(r.pet2, EnumDeep.Container1.Container2.Animal.HARE);
  });
});
