// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchManualInt', () => {
  it('parses test properly', async () => {
    const { SwitchManualInt } = await import('../compiled/SwitchManualInt.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_opcodes.bin'));
    const r = new SwitchManualInt(io);
    assert.strictEqual(r.opcodes.length, 4);
    assert.strictEqual(r.opcodes[0].code, 83);
    assert.strictEqual(r.opcodes[0].body.value, "foobar");
    assert.strictEqual(r.opcodes[1].code, 73);
    assert.strictEqual(r.opcodes[1].body.value, 66);
    assert.strictEqual(r.opcodes[2].code, 73);
    assert.strictEqual(r.opcodes[2].body.value, 55);
    assert.strictEqual(r.opcodes[3].code, 83);
    assert.strictEqual(r.opcodes[3].body.value, "");
  });
});
