// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprIoPosBits', () => {
  it('parses test properly', async () => {
    const { ExprIoPosBits } = await import('../compiled/ExprIoPosBits.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new ExprIoPosBits(io);
    assert.strictEqual(r.foo, 7);
    assert.strictEqual(r.bar, 12);
    assert.strictEqual(r.baz, true);
    assert.strictEqual(r.qux, 59);
  });
});
