// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('InstanceStd', () => {
  it('parses test properly', async () => {
    const { InstanceStd } = await import('../compiled/testformats/InstanceStd.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_encodings.bin'));
    const r = new InstanceStd(io);
    assert.strictEqual(r.header, "Some ");
  });
});
