// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatEosStruct', () => {
  it('parses test properly', async () => {
    const { RepeatEosStruct } = await import('../compiled/testformats/RepeatEosStruct.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_eos_struct.bin'));
    const r = new RepeatEosStruct(io);
    assert.strictEqual(r.chunks.length, 2);
    assert.strictEqual(r.chunks[0].offset, 0);
    assert.strictEqual(r.chunks[0].len, 66);
    assert.strictEqual(r.chunks[1].offset, 66);
    assert.strictEqual(r.chunks[1].len, 2069);
  });
});
