// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumLongRangeS', () => {
  it('parses test properly', async () => {
    const { EnumLongRangeS } = await import('#testformats/EnumLongRangeS.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_long_range_s.bin'));
    const r = new EnumLongRangeS(io);
    assert.strictEqual(r.f1, EnumLongRangeS.Constants.LONG_MIN);
    assert.strictEqual(r.f2, EnumLongRangeS.Constants.INT_BELOW_MIN);
    assert.strictEqual(r.f3, EnumLongRangeS.Constants.INT_MIN);
    assert.strictEqual(r.f4, EnumLongRangeS.Constants.ZERO);
    assert.strictEqual(r.f5, EnumLongRangeS.Constants.INT_MAX);
    assert.strictEqual(r.f6, EnumLongRangeS.Constants.INT_OVER_MAX);
    assert.strictEqual(r.f7, EnumLongRangeS.Constants.LONG_MAX);
  });
});
