// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NestedTypes3', () => {
  it('parses test properly', async () => {
    const { NestedTypes3 } = await import('#testformats/NestedTypes3.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new NestedTypes3(io);
    assert.strictEqual(r.aCc.valueCc, 80);
    assert.strictEqual(r.aCD.valueD, 65);
    assert.strictEqual(r.b.valueB, 67);
    assert.strictEqual(r.b.aCc.valueCc, 75);
    assert.strictEqual(r.b.aCD.valueD, 45);
  });
});
