// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsCallExtraParens', () => {
  it('parses test properly', async () => {
    const { ParamsCallExtraParens } = await import('#testformats/ParamsCallExtraParens.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new ParamsCallExtraParens(io);
    assert.strictEqual(r.buf1.body, "foo|b");
  });
});
