// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatEosTermBytes', () => {
  it('parses test properly', async () => {
    const { RepeatEosTermBytes } = await import('../compiled/RepeatEosTermBytes.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_rotate.bin'));
    const r = new RepeatEosTermBytes(io);
    assert.strictEqual(r.records.length, 2);
    assert.deepStrictEqual(r.records[0], new Uint8Array([9, 172, 141, 141, 237, 186, 123, 147, 99, 35, 1, 42, 52, 178]));
    assert.deepStrictEqual(r.records[1], new Uint8Array([57, 178]));
  });
});
