// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprIfIntOps', () => {
  it('parses test properly', async () => {
    const { ExprIfIntOps } = await import('#testformats/ExprIfIntOps.js');
    const io = new KaitaiStream(fs.readFileSync('src/instance_io.bin'));
    const r = new ExprIfIntOps(io);
    assert.strictEqual(r.key, 3);
    assert.deepStrictEqual(r.bytes, new Uint8Array([252, 252, 252, 253, 9, 3, 3, 3]));
    assert.strictEqual(r.bytesSubKey, 253);
    assert.strictEqual(r.itemsSubKey, -3);
  });
});
