// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ImportsParamsDefArrayUsertypeImported', () => {
  it('parses test properly', async () => {
    const { ImportsParamsDefArrayUsertypeImported } = await import('#testformats/ImportsParamsDefArrayUsertypeImported.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new ImportsParamsDefArrayUsertypeImported(io);
    assert.strictEqual(r.hws.length, 2);
    assert.strictEqual(r.hws[0].one, 236);
    assert.strictEqual(r.hws[1].one, 187);
    assert.strictEqual(r.two.hw0One, 236);
    assert.strictEqual(r.two.hw1One, 187);
  });
});
