// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NestedTypes2', () => {
  it('parses test properly', async () => {
    const { NestedTypes2 } = await import('../compiled/NestedTypes2.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new NestedTypes2(io);
    assert.strictEqual(r.one.typedAtRoot.valueB, 80);
    assert.strictEqual(r.one.typedHere1.valueC, 65);
    assert.strictEqual(r.one.typedHere1.typedHere.valueD, 67);
    assert.strictEqual(r.one.typedHere1.typedParent.valueCc, 75);
    assert.strictEqual(r.one.typedHere1.typedRoot.valueB, 45);
    assert.strictEqual(r.one.typedHere2.valueCc, 49);
    assert.strictEqual(r.two.valueB, -1);
  });
});
