// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumToIClassBorder1', () => {
  it('parses test properly', async () => {
    const { EnumToIClassBorder1 } = await import('../compiled/EnumToIClassBorder1.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new EnumToIClassBorder1(io);
    assert.strictEqual(r.pet1, EnumToIClassBorder1.Animal.CAT);
    assert.strictEqual(r.pet2, EnumToIClassBorder1.Animal.CHICKEN);
    assert.strictEqual(r.checker.isDog, true);
  });
});
