// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprSizeofType0', () => {
  it('parses test properly', async () => {
    const { ExprSizeofType0 } = await import('#testformats/ExprSizeofType0.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ExprSizeofType0(io);
    assert.strictEqual(r.sizeofBlock, (1 + 4) + 2);
  });
});
