// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailAnyofInt', () => {
  it('parses test properly', async () => {
    const { ValidFailAnyofInt } = await import('../compiled/testformats/ValidFailAnyofInt.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    assert.ok(KaitaiStream.ValidationNotAnyOfError);
    assert.throws(() => new ValidFailAnyofInt(io), KaitaiStream.ValidationNotAnyOfError);
  });
});
