// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatEosBytes', () => {
  it('parses test properly', async () => {
    const { RepeatEosBytes } = await import('../compiled/RepeatEosBytes.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_until_process.bin'));
    const r = new RepeatEosBytes(io);
    assert.strictEqual(r.records.length, 3);
    assert.deepStrictEqual(r.records[0], new Uint8Array([232, 186, 170, 170, 170]));
    assert.deepStrictEqual(r.records[1], new Uint8Array([250, 158, 184, 170, 170]));
    assert.deepStrictEqual(r.records[2], new Uint8Array([170, 85, 85, 85, 85]));
  });
});
