// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('Imports0', () => {
  it('parses test properly', async () => {
    const { Imports0 } = await import('../compiled/testformats/Imports0.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new Imports0(io);
    assert.strictEqual(r.two, 80);
    assert.strictEqual(r.hw.one, 65);
    assert.strictEqual(r.hwOne, 65);
  });
});
