// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchManualEnumInvalid', () => {
  it('parses test properly', async () => {
    const { SwitchManualEnumInvalid } = await import('../compiled/SwitchManualEnumInvalid.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new SwitchManualEnumInvalid(io);
    assert.strictEqual(r.opcodes.length, 2);
    assert.strictEqual(r.opcodes[0].code, 255);
    assert.strictEqual(r.opcodes[0].body, undefined);
    assert.strictEqual(r.opcodes[1].code, 1);
    assert.strictEqual(r.opcodes[1].body, undefined);
  });
});
