// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('CastToTop', () => {
  it('parses test properly', async () => {
    const { CastToTop } = await import('../compiled/testformats/CastToTop.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new CastToTop(io);
    assert.strictEqual(r.code, 80);
    assert.strictEqual(r.header.code, 65);
    assert.strictEqual(r.headerCasted.code, 65);
  });
});
