// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ZlibSurrounded', () => {
  it('parses test properly', async () => {
    const { ZlibSurrounded } = await import('../compiled/ZlibSurrounded.js');
    const io = new KaitaiStream(fs.readFileSync('src/zlib_surrounded.bin'));
    const r = new ZlibSurrounded(io);
    assert.strictEqual(r.zlib.num, -1);
  });
});
