// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumIntRangeU', () => {
  it('parses test properly', async () => {
    const { EnumIntRangeU } = await import('../compiled/testformats/EnumIntRangeU.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_int_range_u.bin'));
    const r = new EnumIntRangeU(io);
    assert.strictEqual(r.f1, EnumIntRangeU.Constants.ZERO);
    assert.strictEqual(r.f2, EnumIntRangeU.Constants.INT_MAX);
  });
});
