// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StrLiterals2', () => {
  it('parses test properly', async () => {
    const { StrLiterals2 } = await import('#testformats/StrLiterals2.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new StrLiterals2(io);
    assert.strictEqual(r.dollar1, "$foo");
    assert.strictEqual(r.dollar2, "${foo}");
    assert.strictEqual(r.hash, "#{foo}");
    assert.strictEqual(r.atSign, "@foo");
  });
});
