// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailMinInt', () => {
  it('parses test properly', async () => {
    const { ValidFailMinInt } = await import('../compiled/testformats/ValidFailMinInt.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    assert.ok(KaitaiStream.ValidationLessThanError);
    assert.throws(() => new ValidFailMinInt(io), KaitaiStream.ValidationLessThanError);
  });
});
