// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprBytesOps', () => {
  it('parses test properly', async () => {
    const { ExprBytesOps } = await import('../compiled/ExprBytesOps.js');
    const io = new KaitaiStream(fs.readFileSync('src/nav_parent_switch.bin'));
    const r = new ExprBytesOps(io);
    assert.strictEqual(r.oneSize, 3);
    assert.strictEqual(r.oneFirst, 1);
    assert.strictEqual(r.oneMid, 66);
    assert.strictEqual(r.oneLast, 255);
    assert.strictEqual((r.oneLast).toString(), "255");
    assert.strictEqual(r.oneMin, 1);
    assert.strictEqual(r.oneMax, 255);
    assert.strictEqual((r.oneMax).toString(), "255");
    assert.strictEqual(r.twoSize, 3);
    assert.strictEqual(r.twoFirst, 65);
    assert.strictEqual(r.twoMid, 255);
    assert.strictEqual((r.twoMid).toString(), "255");
    assert.strictEqual(r.twoLast, 75);
    assert.strictEqual(r.twoMin, 65);
    assert.strictEqual(r.twoMax, 255);
    assert.strictEqual((r.twoMax).toString(), "255");
  });
});
