// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('JsSignedRightShift', () => {
  it('parses test properly', async () => {
    const { JsSignedRightShift } = await import('#testformats/JsSignedRightShift.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new JsSignedRightShift(io);
    assert.strictEqual(r.shouldBe40000000, 1073741824);
    assert.strictEqual(r.shouldBeA00000, 10485760);
  });
});
