// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsPassStruct', () => {
  it('parses test properly', async () => {
    const { ParamsPassStruct } = await import('../compiled/ParamsPassStruct.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new ParamsPassStruct(io);
    assert.strictEqual(r.first.foo, 255);
    assert.strictEqual(r.one.bar.qux, 1);
    assert.strictEqual(r.one.foo.foo, 255);
    assert.strictEqual(r.one.bar.foo.foo, 255);
  });
});
