// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ImportsRel1', () => {
  it('parses test properly', async () => {
    const { ImportsRel1 } = await import('../compiled/ImportsRel1.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ImportsRel1(io);
    assert.strictEqual(r.one, 80);
    assert.strictEqual(r.two.one, 65);
    assert.strictEqual(r.two.two.one, 67);
  });
});
