// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprIoTernary', () => {
  it('parses test properly', async () => {
    const { ExprIoTernary } = await import('../compiled/testformats/ExprIoTernary.js');
    const io = new KaitaiStream(fs.readFileSync('src/if_struct.bin'));
    const r = new ExprIoTernary(io);
    assert.strictEqual(r.oneOrTwoIoSize1, 8);
    assert.strictEqual(r.oneOrTwoIoSize2, 8);
    assert.strictEqual(r.oneOrTwoIoSizeAdd3, 11);
  });
});
