// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumToI', () => {
  it('parses test properly', async () => {
    const { EnumToI } = await import('../compiled/EnumToI.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new EnumToI(io);
    assert.strictEqual(r.pet1, EnumToI.Animal.CAT);
    assert.strictEqual(r.pet2, EnumToI.Animal.CHICKEN);
    assert.strictEqual(r.pet1I, 7);
    assert.strictEqual(r.pet1IToS, "7");
    assert.strictEqual(r.pet1Mod, 32775);
    assert.strictEqual(r.oneLtTwo, true);
    assert.strictEqual(r.pet1EqInt, true);
    assert.strictEqual(r.pet2EqInt, false);
  });
});
