// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NavParent3', () => {
  it('parses test properly', async () => {
    const { NavParent3 } = await import('#testformats/NavParent3.js');
    const io = new KaitaiStream(fs.readFileSync('src/nav_parent2.bin'));
    const r = new NavParent3(io);
    assert.strictEqual(r.ofsTags, 8);
    assert.strictEqual(r.numTags, 2);
    assert.strictEqual(r.tags[0].name, "RAHC");
    assert.strictEqual(r.tags[0].ofs, 32);
    assert.strictEqual(r.tags[0].numItems, 3);
    assert.strictEqual(r.tags[0].tagContent.content, "foo");
    assert.strictEqual(r.tags[1].name, "RAHC");
    assert.strictEqual(r.tags[1].ofs, 35);
    assert.strictEqual(r.tags[1].numItems, 6);
    assert.strictEqual(r.tags[1].tagContent.content, "barbaz");
  });
});
