// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('Enum0', () => {
  it('parses test properly', async () => {
    const { Enum0 } = await import('#testformats/Enum0.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new Enum0(io);
    assert.strictEqual(r.pet1, Enum0.Animal.CAT);
    assert.strictEqual(r.pet2, Enum0.Animal.CHICKEN);
  });
});
