// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchRepeatExpr', () => {
  it('parses test properly', async () => {
    const { SwitchRepeatExpr } = await import('#testformats/SwitchRepeatExpr.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_integers.bin'));
    const r = new SwitchRepeatExpr(io);
    assert.strictEqual(r.codes.length, 3);
    assert.strictEqual(r.codes[0], 1);
    assert.strictEqual(r.codes[1], 7);
    assert.strictEqual(r.codes[2], 2);
    assert.deepStrictEqual(r.body[0].first, new Uint8Array([64, 64, 4, 55]));
    assert.deepStrictEqual(r.body[1].second, new Uint8Array([19, 0, 0, 8]));
    assert.deepStrictEqual(r.body[2].first, new Uint8Array([55, 19, 0, 0]));
  });
});
