// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('TermStrzUtf16V3', () => {
  it('parses test properly', async () => {
    const { TermStrzUtf16V3 } = await import('../compiled/TermStrzUtf16V3.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz_utf16.bin'));
    const r = new TermStrzUtf16V3(io);
    assert.strictEqual(r.s1, "a\u0200b");
    assert.strictEqual(r.term, 0);
    assert.strictEqual(r.s2, "c\u0200d");
    assert.strictEqual(r.s3, "");
  });
});
