// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('YamlInts', () => {
  it('parses test properly', async () => {
    const { YamlInts } = await import('../compiled/testformats/YamlInts.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new YamlInts(io);
    assert.strictEqual(r.testU4Dec, 4294967295);
    assert.strictEqual(r.testU4Hex, 4294967295);
    assert.strictEqual(r.testU8Dec, 18446744073709551615);
    assert.strictEqual(r.testU8Hex, 18446744073709551615);
  });
});
