// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsSignedShiftB32Le', () => {
  it('parses test properly', async () => {
    const { BitsSignedShiftB32Le } = await import('#testformats/BitsSignedShiftB32Le.js');
    const io = new KaitaiStream(fs.readFileSync('src/bits_signed_shift_b32_le.bin'));
    const r = new BitsSignedShiftB32Le(io);
    assert.strictEqual(r.a, 0);
    assert.strictEqual(r.b, 255);
  });
});
