// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessRepeatUsertype', () => {
  it('parses test properly', async () => {
    const { ProcessRepeatUsertype } = await import('#testformats/ProcessRepeatUsertype.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new ProcessRepeatUsertype(io);
    assert.strictEqual(r.blocks[0].a, -1975704206);
    assert.strictEqual(r.blocks[0].b, 20);
    assert.strictEqual(r.blocks[1].a, 279597642);
    assert.strictEqual(r.blocks[1].b, 68);
  });
});
