// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailExpr', () => {
  it('parses test properly', async () => {
    const { ValidFailExpr } = await import('#testformats/ValidFailExpr.js');
    const io = new KaitaiStream(fs.readFileSync('src/nav_parent_switch.bin'));
    assert.ok(KaitaiStream.ValidationExprError);
    assert.throws(() => new ValidFailExpr(io), KaitaiStream.ValidationExprError);
  });
});
