// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('Expr0', () => {
  it('parses test properly', async () => {
    const { Expr0 } = await import('#testformats/Expr0.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_encodings.bin'));
    const r = new Expr0(io);
    assert.strictEqual(r.mustBeF7, 247);
    assert.strictEqual(r.mustBeAbc123, "abc123");
  });
});
