// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprToITrailing', () => {
  it('parses test properly', async () => {
    const { ExprToITrailing } = await import('#testformats/ExprToITrailing.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new ExprToITrailing(io);
    assert.throws(
      () => {
        r.toIR10;
      },
      { name: 'KaitaiStream.ConversionError' }
    )
    assert.strictEqual(r.toIR16, 152517308);
    assert.throws(
      () => {
        r.toIGarbage;
      },
      { name: 'KaitaiStream.ConversionError' }
    )
  });
});
