// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessRepeatBytes', () => {
  it('parses test properly', async () => {
    const { ProcessRepeatBytes } = await import('../compiled/ProcessRepeatBytes.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new ProcessRepeatBytes(io);
    assert.deepStrictEqual(r.bufs[0], new Uint8Array([114, 37, 61, 138, 20]));
    assert.deepStrictEqual(r.bufs[1], new Uint8Array([74, 82, 170, 16, 68]));
  });
});
