// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsByteAligned', () => {
  it('parses test properly', async () => {
    const { BitsByteAligned } = await import('../compiled/BitsByteAligned.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new BitsByteAligned(io);
    assert.strictEqual(r.one, 20);
    assert.strictEqual(r.byte1, 65);
    assert.strictEqual(r.two, 2);
    assert.strictEqual(r.three, false);
    assert.deepStrictEqual(r.byte2, new Uint8Array([75]));
    assert.strictEqual(r.four, 2892);
    assert.strictEqual(r.byte3.inner, 524282);
    assert.strictEqual(r.fullByte, 65);
    assert.strictEqual(r.byte4, 67);
    assert.strictEqual(r.five, 1231701);
    assert.deepStrictEqual(r.bytesTerm, new Uint8Array([45, 68, 69]));
    assert.strictEqual(r.six, 70);
  });
});
