// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessRepeatUsertypeDynargRotate', () => {
  it('parses test properly', async () => {
    const { ProcessRepeatUsertypeDynargRotate } = await import('#testformats/ProcessRepeatUsertypeDynargRotate.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_rotate.bin'));
    const r = new ProcessRepeatUsertypeDynargRotate(io);
    assert.strictEqual(r.blocksRol[0].a, 25928);
    assert.strictEqual(r.blocksRol[1].a, 46902);
    assert.strictEqual(r.blocksRor[0].a, 29295);
    assert.strictEqual(r.blocksRor[1].a, 16584);
    assert.strictEqual(r.blocksRor[2].a, 22810);
    assert.strictEqual(r.blocksB.dummy, 178);
    assert.strictEqual(r.blocksB.blocksRol0B, 108);
    assert.strictEqual(r.blocksB.blocksRol1B, 234);
    assert.strictEqual(r.blocksB.blocksRor0B, 108);
    assert.strictEqual(r.blocksB.blocksRor1B, 138);
    assert.strictEqual(r.blocksB.blocksRor2B, 156);
  });
});
