// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailRangeBytes', () => {
  it('parses test properly', async () => {
    const { ValidFailRangeBytes } = await import('#testformats/ValidFailRangeBytes.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    assert.ok(KaitaiStream.ValidationGreaterThanError);
    assert.throws(() => new ValidFailRangeBytes(io), KaitaiStream.ValidationGreaterThanError);
  });
});
