// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('StrEos', () => {
  it('parses test properly', async () => {
    const { StrEos } = await import('../compiled/testformats/StrEos.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new StrEos(io);
    assert.strictEqual(r.str, "foo|bar|baz@");
  });
});
