// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsEnum', () => {
  it('parses test properly', async () => {
    const { ParamsEnum } = await import('../compiled/ParamsEnum.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new ParamsEnum(io);
    assert.strictEqual(r.one, ParamsEnum.Animal.CAT);
    assert.strictEqual(r.invokeWithParam.isCat, true);
  });
});
