// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessTermStruct', () => {
  it('parses test properly', async () => {
    const { ProcessTermStruct } = await import('../compiled/ProcessTermStruct.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new ProcessTermStruct(io);
    assert.deepStrictEqual(r.s1.value, new Uint8Array([70, 79, 79]));
    assert.deepStrictEqual(r.s2.value, new Uint8Array([66, 65, 82]));
    assert.deepStrictEqual(r.s3.value, new Uint8Array([92, 66, 65, 90, 32]));
  });
});
