// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EofExceptionSwitchUser', () => {
  it('parses test properly', async () => {
    const { EofExceptionSwitchUser } = await import('../compiled/EofExceptionSwitchUser.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    assert.ok(KaitaiStream.EOFError);
    assert.throws(() => new EofExceptionSwitchUser(io), KaitaiStream.EOFError);
  });
});
