// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NavRoot', () => {
  it('parses test properly', async () => {
    const { NavRoot } = await import('#testformats/NavRoot.js');
    const io = new KaitaiStream(fs.readFileSync('src/nav.bin'));
    const r = new NavRoot(io);
    assert.strictEqual(r.header.qtyEntries, 2);
    assert.strictEqual(r.header.filenameLen, 8);
    assert.strictEqual(r.index.entries.length, 2);
    assert.strictEqual(r.index.entries[0].filename, "FIRST___");
    assert.strictEqual(r.index.entries[1].filename, "SECOND__");
  });
});
