// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('Integers', () => {
  it('parses test properly', async () => {
    const { Integers } = await import('#testformats/Integers.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new Integers(io);
    assert.strictEqual(r.uint8, 255);
    assert.strictEqual(r.uint16, 65535);
    assert.strictEqual(r.uint32, 4294967295);
    assert.strictEqual(r.uint64, 18446744073709551615);
    assert.strictEqual(r.sint8, -1);
    assert.strictEqual(r.sint16, -1);
    assert.strictEqual(r.sint32, -1);
    assert.strictEqual(r.sint64, -1);
    assert.strictEqual(r.uint16le, 66);
    assert.strictEqual(r.uint32le, 66);
    assert.strictEqual(r.uint64le, 66);
    assert.strictEqual(r.sint16le, -66);
    assert.strictEqual(r.sint32le, -66);
    assert.strictEqual(r.sint64le, -66);
    assert.strictEqual(r.uint16be, 66);
    assert.strictEqual(r.uint32be, 66);
    assert.strictEqual(r.uint64be, 66);
    assert.strictEqual(r.sint16be, -66);
    assert.strictEqual(r.sint32be, -66);
    assert.strictEqual(r.sint64be, -66);
  });
});
