// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('TermStrz', () => {
  it('parses test properly', async () => {
    const { TermStrz } = await import('#testformats/TermStrz.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TermStrz(io);
    assert.strictEqual(r.s1, "foo");
    assert.strictEqual(r.s2, "bar");
    assert.strictEqual(r.s3, "|baz@");
  });
});
