// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessRotate', () => {
  it('parses test properly', async () => {
    const { ProcessRotate } = await import('../compiled/ProcessRotate.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_rotate.bin'));
    const r = new ProcessRotate(io);
    assert.deepStrictEqual(r.buf1, new Uint8Array([72, 101, 108, 108, 111]));
    assert.deepStrictEqual(r.buf2, new Uint8Array([87, 111, 114, 108, 100]));
    assert.deepStrictEqual(r.buf3, new Uint8Array([84, 104, 101, 114, 101]));
  });
});
