// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('FloatToI', () => {
  it('parses test properly', async () => {
    const { FloatToI } = await import('../compiled/testformats/FloatToI.js');
    const io = new KaitaiStream(fs.readFileSync('src/floating_points.bin'));
    const r = new FloatToI(io);
    assert(Math.abs(r.singleValue - 0.5) < 1e-6);
    assert(Math.abs(r.doubleValue - 0.25) < 1e-6);
    assert(Math.abs(r.singleValueIf - 0.5) < 1e-6);
    assert(Math.abs(r.doubleValueIf - 0.25) < 1e-6);
    assert.strictEqual(r.singleI, 0);
    assert.strictEqual(r.doubleI, 0);
    assert.strictEqual(r.singleIfI, 0);
    assert.strictEqual(r.doubleIfI, 0);
    assert.strictEqual(r.float1I, 1);
    assert.strictEqual(r.float2I, 1);
    assert.strictEqual(r.float3I, 1);
    assert.strictEqual(r.float4I, -2);
    assert.strictEqual(r.calcIfI, 13);
  });
});
