// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('Enum1', () => {
  it('parses test properly', async () => {
    const { Enum1 } = await import('#testformats/Enum1.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new Enum1(io);
    assert.strictEqual(r.main.submain.pet1, Enum1.MainObj.Animal.CAT);
    assert.strictEqual(r.main.submain.pet2, Enum1.MainObj.Animal.CHICKEN);
  });
});
