// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('DefaultBitEndianMod', () => {
  it('parses test properly', async () => {
    const { DefaultBitEndianMod } = await import('../compiled/DefaultBitEndianMod.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new DefaultBitEndianMod(io);
    assert.strictEqual(r.main.one, 336);
    assert.strictEqual(r.main.two, 8608);
    assert.strictEqual(r.main.nest.two, 11595);
    assert.strictEqual(r.main.nestBe.two, 12799);
  });
});
