// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatNStrz', () => {
  it('parses test properly', async () => {
    const { RepeatNStrz } = await import('#testformats/RepeatNStrz.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_n_strz.bin'));
    const r = new RepeatNStrz(io);
    assert.strictEqual(r.qty, 2);
    assert.deepStrictEqual(r.lines, ["foo", "bar"]);
  });
});
