// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('TypeIntUnaryOp', () => {
  it('parses test properly', async () => {
    const { TypeIntUnaryOp } = await import('#testformats/TypeIntUnaryOp.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new TypeIntUnaryOp(io);
    assert.strictEqual(r.valueS2, 16720);
    assert.strictEqual(r.valueS8, 4706543082108963651);
    assert.strictEqual(r.unaryS2, -16720);
    assert.strictEqual(r.unaryS8, -4706543082108963651);
  });
});
