// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsPassBool', () => {
  it('parses test properly', async () => {
    const { ParamsPassBool } = await import('../compiled/ParamsPassBool.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new ParamsPassBool(io);
    assert.strictEqual(r.sFalse, false);
    assert.strictEqual(r.sTrue, true);
    assert.strictEqual(r.seqB1.arg, true);
    assert.strictEqual(r.seqB1.foo.length, 1);
    assert.strictEqual(r.seqBool.arg, false);
    assert.strictEqual(r.seqBool.foo.length, 2);
    assert.strictEqual(r.literalB1.arg, false);
    assert.strictEqual(r.literalB1.foo.length, 2);
    assert.strictEqual(r.literalBool.arg, true);
    assert.strictEqual(r.literalBool.foo.length, 1);
    assert.strictEqual(r.instB1.arg, true);
    assert.strictEqual(r.instB1.foo.length, 1);
    assert.strictEqual(r.instBool.arg, false);
    assert.strictEqual(r.instBool.foo.length, 2);
  });
});
