// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsPassArrayStr', () => {
  it('parses test properly', async () => {
    const { ParamsPassArrayStr } = await import('#testformats/ParamsPassArrayStr.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new ParamsPassArrayStr(io);
    assert.strictEqual(r.passStrArray.strs.length, 3);
    assert.strictEqual(r.passStrArray.strs[0], "fo");
    assert.strictEqual(r.passStrArray.strs[1], "o|");
    assert.strictEqual(r.passStrArray.strs[2], "ba");
    assert.strictEqual(r.passStrArrayCalc.strs.length, 2);
    assert.strictEqual(r.passStrArrayCalc.strs[0], "aB");
    assert.strictEqual(r.passStrArrayCalc.strs[1], "Cd");
  });
});
