// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NavParentVsValueInst', () => {
  it('parses test properly', async () => {
    const { NavParentVsValueInst } = await import('#testformats/NavParentVsValueInst.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new NavParentVsValueInst(io);
    assert.strictEqual(r.s1, "foo");
  });
});
