// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StrEosPadTerm', () => {
  it('parses test properly', async () => {
    const { StrEosPadTerm } = await import('#testformats/StrEosPadTerm.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term.bin'));
    const r = new StrEosPadTerm(io);
    assert.strictEqual(r.strPad.value, "str1");
    assert.strictEqual(r.strTerm.value, "str2foo");
    assert.strictEqual(r.strTermAndPad.value, "str+++3bar+++");
    assert.strictEqual(r.strTermInclude.value, "str4baz@");
  });
});
