// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessStructPadTerm', () => {
  it('parses test properly', async () => {
    const { ProcessStructPadTerm } = await import('../compiled/testformats/ProcessStructPadTerm.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term.bin'));
    const r = new ProcessStructPadTerm(io);
    assert.deepStrictEqual(r.strPad.value, new Uint8Array([102, 97, 103, 36]));
    assert.deepStrictEqual(r.strTerm.value, new Uint8Array([102, 97, 103, 39, 115, 122, 122]));
    assert.deepStrictEqual(r.strTermAndPad.value, new Uint8Array([102, 97, 103, 62, 62, 62, 38, 119, 116, 103, 62, 62, 62]));
    assert.deepStrictEqual(r.strTermInclude.value, new Uint8Array([102, 97, 103, 33, 119, 116, 111, 85]));
  });
});
