// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsUnalignedB64Be', () => {
  it('parses test properly', async () => {
    const { BitsUnalignedB64Be } = await import('../compiled/testformats/BitsUnalignedB64Be.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new BitsUnalignedB64Be(io);
    assert.strictEqual(r.a, true);
    assert.strictEqual(r.b, 15670070570729969769);
    assert.strictEqual(r.c, 14);
  });
});
