// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NestedTypesImport', () => {
  it('parses test properly', async () => {
    const { NestedTypesImport } = await import('#testformats/NestedTypesImport.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new NestedTypesImport(io);
    assert.strictEqual(r.aCc.valueCc, 80);
    assert.strictEqual(r.aCD.valueD, 65);
    assert.strictEqual(r.b.valueB, 67);
    assert.strictEqual(r.b.aCc.valueCc, 75);
    assert.strictEqual(r.b.aCD.valueD, 45);
    assert.strictEqual(r.aCc._parent, undefined);
    assert.strictEqual(r.aCc._root, undefined);
    assert.strictEqual(r.aCD._parent, undefined);
    assert.strictEqual(r.aCD._root, undefined);
    assert.strictEqual(r.b._parent, undefined);
    assert.strictEqual(r.b._root, undefined);
  });
});
