// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailRepeatMaxInt', () => {
  it('parses test properly', async () => {
    const { ValidFailRepeatMaxInt } = await import('../compiled/ValidFailRepeatMaxInt.js');
    const io = new KaitaiStream(fs.readFileSync('src/nav_parent_switch.bin'));
    assert.ok(KaitaiStream.ValidationGreaterThanError);
    assert.throws(() => new ValidFailRepeatMaxInt(io), KaitaiStream.ValidationGreaterThanError);
  });
});
