// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailInEnum', () => {
  it('parses test properly', async () => {
    const { ValidFailInEnum } = await import('#testformats/ValidFailInEnum.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    assert.ok(KaitaiStream.ValidationNotInEnumError);
    assert.throws(() => new ValidFailInEnum(io), KaitaiStream.ValidationNotInEnumError);
  });
});
