// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('IndexToParamUntil', () => {
  it('parses test properly', async () => {
    const { IndexToParamUntil } = await import('../compiled/IndexToParamUntil.js');
    const io = new KaitaiStream(fs.readFileSync('src/index_sizes.bin'));
    const r = new IndexToParamUntil(io);
    assert.strictEqual(r.qty, 3);
    assert.strictEqual(r.sizes[0], 1);
    assert.strictEqual(r.sizes[1], 8);
    assert.strictEqual(r.sizes[2], 4);
    assert.strictEqual(r.blocks[0].buf, "A");
    assert.strictEqual(r.blocks[1].buf, "BBBBBBBB");
    assert.strictEqual(r.blocks[2].buf, "CCCC");
  });
});
