// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('FixedStruct', () => {
  it('parses test properly', async () => {
    const { FixedStruct } = await import('../compiled/FixedStruct.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new FixedStruct(io);
    assert.strictEqual(r.hdr.uint8, 255);
    assert.strictEqual(r.hdr.uint16, 65535);
    assert.strictEqual(r.hdr.uint32, 4294967295);
    assert.strictEqual(r.hdr.uint64, 18446744073709551615);
    assert.strictEqual(r.hdr.sint8, -1);
    assert.strictEqual(r.hdr.sint16, -1);
    assert.strictEqual(r.hdr.sint32, -1);
    assert.strictEqual(r.hdr.sint64, -1);
    assert.strictEqual(r.hdr.uint16le, 66);
    assert.strictEqual(r.hdr.uint32le, 66);
    assert.strictEqual(r.hdr.uint64le, 66);
    assert.strictEqual(r.hdr.sint16le, -66);
    assert.strictEqual(r.hdr.sint32le, -66);
    assert.strictEqual(r.hdr.sint64le, -66);
    assert.strictEqual(r.hdr.uint16be, 66);
    assert.strictEqual(r.hdr.uint32be, 66);
    assert.strictEqual(r.hdr.uint64be, 66);
    assert.strictEqual(r.hdr.sint16be, -66);
    assert.strictEqual(r.hdr.sint32be, -66);
    assert.strictEqual(r.hdr.sint64be, -66);
  });
});
