// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('PositionAbs', () => {
  it('parses test properly', async () => {
    const { PositionAbs } = await import('../compiled/PositionAbs.js');
    const io = new KaitaiStream(fs.readFileSync('src/position_abs.bin'));
    const r = new PositionAbs(io);
    assert.strictEqual(r.indexOffset, 32);
    assert.strictEqual(r.index.entry, "foo");
  });
});
