// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('Expr1', () => {
  it('parses test properly', async () => {
    const { Expr1 } = await import('../compiled/Expr1.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_encodings.bin'));
    const r = new Expr1(io);
    assert.strictEqual(r.lenOf1, 10);
    assert.strictEqual(r.lenOf1Mod, 8);
    assert.strictEqual(r.str1, "Some ASC");
    assert.strictEqual(r.str1Len, 8);
  });
});
