// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('InstanceInRepeatExpr', () => {
  it('parses test properly', async () => {
    const { InstanceInRepeatExpr } = await import('../compiled/InstanceInRepeatExpr.js');
    const io = new KaitaiStream(fs.readFileSync('src/instance_in_repeat_expr.bin'));
    const r = new InstanceInRepeatExpr(io);
    assert.strictEqual(r.chunks.length, 2);
    assert.strictEqual(r.chunks[0].offset, 16);
    assert.strictEqual(r.chunks[0].len, 8312);
    assert.strictEqual(r.chunks[1].offset, 8328);
    assert.strictEqual(r.chunks[1].len, 15);
  });
});
