// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchManualStrElse', () => {
  it('parses test properly', async () => {
    const { SwitchManualStrElse } = await import('../compiled/SwitchManualStrElse.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_opcodes2.bin'));
    const r = new SwitchManualStrElse(io);
    assert.strictEqual(r.opcodes.length, 4);
    assert.strictEqual(r.opcodes[0].code, "S");
    assert.strictEqual(r.opcodes[0].body.value, "foo");
    assert.strictEqual(r.opcodes[1].code, "X");
    assert.strictEqual(r.opcodes[1].body.filler, 66);
    assert.strictEqual(r.opcodes[2].code, "Y");
    assert.strictEqual(r.opcodes[2].body.filler, 51966);
    assert.strictEqual(r.opcodes[3].code, "I");
    assert.strictEqual(r.opcodes[3].body.value, 7);
  });
});
