// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprStrEncodings', () => {
  it('parses test properly', async () => {
    const { ExprStrEncodings } = await import('../compiled/ExprStrEncodings.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_encodings.bin'));
    const r = new ExprStrEncodings(io);
    assert.strictEqual(r.str1Eq, true);
    assert.strictEqual(r.str2Eq, true);
    assert.strictEqual(r.str3Eq, true);
    assert.strictEqual(r.str3EqStr2, true);
    assert.strictEqual(r.str4Eq, true);
    assert.strictEqual(r.str4GtStrCalc, true);
    assert.strictEqual(r.str4GtStrFromBytes, true);
  });
});
