// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchManualEnum', () => {
  it('parses test properly', async () => {
    const { SwitchManualEnum } = await import('../compiled/testformats/SwitchManualEnum.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_opcodes.bin'));
    const r = new SwitchManualEnum(io);
    assert.strictEqual(r.opcodes.length, 4);
    assert.strictEqual(r.opcodes[0].code, SwitchManualEnum.Opcode.CodeEnum.STRVAL);
    assert.strictEqual(r.opcodes[0].body.value, "foobar");
    assert.strictEqual(r.opcodes[1].code, SwitchManualEnum.Opcode.CodeEnum.INTVAL);
    assert.strictEqual(r.opcodes[1].body.value, 66);
    assert.strictEqual(r.opcodes[2].code, SwitchManualEnum.Opcode.CodeEnum.INTVAL);
    assert.strictEqual(r.opcodes[2].body.value, 55);
    assert.strictEqual(r.opcodes[3].code, SwitchManualEnum.Opcode.CodeEnum.STRVAL);
    assert.strictEqual(r.opcodes[3].body.value, "");
  });
});
