// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumDeepLiterals', () => {
  it('parses test properly', async () => {
    const { EnumDeepLiterals } = await import('../compiled/EnumDeepLiterals.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new EnumDeepLiterals(io);
    assert.strictEqual(r.isPet1Ok, true);
    assert.strictEqual(r.isPet2Ok, true);
  });
});
