// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('Expr3', () => {
  it('parses test properly', async () => {
    const { Expr3 } = await import('../compiled/Expr3.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new Expr3(io);
    assert.strictEqual(r.one, 80);
    assert.strictEqual(r.two, "ACK");
    assert.strictEqual(r.three, "@ACK");
    assert.strictEqual(r.four, "_ACK_");
    assert.strictEqual(r.isStrEq, true);
    assert.strictEqual(r.isStrNe, false);
    assert.strictEqual(r.isStrLt, true);
    assert.strictEqual(r.isStrGt, false);
    assert.strictEqual(r.isStrLe, true);
    assert.strictEqual(r.isStrGe, false);
    assert.strictEqual(r.isStrLt2, true);
    assert.strictEqual(r.testNot, true);
  });
});
