// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatUntilBytesPad', () => {
  it('parses test properly', async () => {
    const { RepeatUntilBytesPad } = await import('../compiled/testformats/RepeatUntilBytesPad.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_until_process.bin'));
    const r = new RepeatUntilBytesPad(io);
    assert.strictEqual(r.records.length, 3);
    assert.deepStrictEqual(r.records[0], new Uint8Array([232, 186]));
    assert.deepStrictEqual(r.records[1], new Uint8Array([250, 158, 184]));
    assert.deepStrictEqual(r.records[2], new Uint8Array([170, 85, 85, 85, 85]));
  });
});
