// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprMod', () => {
  it('parses test properly', async () => {
    const { ExprMod } = await import('../compiled/ExprMod.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ExprMod(io);
    assert.strictEqual(r.intU, 1262698832);
    assert.strictEqual(r.intS, -52947);
    assert.strictEqual(r.modPosConst, 9);
    assert.strictEqual(r.modNegConst, 4);
    assert.strictEqual(r.modPosSeq, 5);
    assert.strictEqual(r.modNegSeq, 2);
  });
});
