// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsPassUsertype', () => {
  it('parses test properly', async () => {
    const { ParamsPassUsertype } = await import('../compiled/ParamsPassUsertype.js');
    const io = new KaitaiStream(fs.readFileSync('src/position_in_seq.bin'));
    const r = new ParamsPassUsertype(io);
    assert.strictEqual(r.first.foo, 1);
    assert.deepStrictEqual(r.one.buf, new Uint8Array([2]));
  });
});
