// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StrPadTermEmpty', () => {
  it('parses test properly', async () => {
    const { StrPadTermEmpty } = await import('../compiled/StrPadTermEmpty.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term_empty.bin'));
    const r = new StrPadTermEmpty(io);
    assert.strictEqual(r.strPad, "");
    assert.strictEqual(r.strTerm, "");
    assert.strictEqual(r.strTermAndPad, "");
    assert.strictEqual(r.strTermInclude, "@");
  });
});
