// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsUnalignedB64Le', () => {
  it('parses test properly', async () => {
    const { BitsUnalignedB64Le } = await import('#testformats/BitsUnalignedB64Le.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new BitsUnalignedB64Le(io);
    assert.strictEqual(r.a, false);
    assert.strictEqual(r.b, 1902324737369038326);
    assert.strictEqual(r.c, 71);
  });
});
