// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('CombineBool', () => {
  it('parses test properly', async () => {
    const { CombineBool } = await import('../compiled/CombineBool.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new CombineBool(io);
    assert.strictEqual(r.boolBit, true);
    assert.strictEqual(r.boolCalcBit, false);
  });
});
