// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('TermStrz2', () => {
  it('parses test properly', async () => {
    const { TermStrz2 } = await import('../compiled/testformats/TermStrz2.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TermStrz2(io);
    assert.strictEqual(r.s1, "foo");
    assert.strictEqual(r.s2, "bar|");
    assert.strictEqual(r.s3, "baz");
  });
});
