// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('TermBytes', () => {
  it('parses test properly', async () => {
    const { TermBytes } = await import('../compiled/testformats/TermBytes.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TermBytes(io);
    assert.deepStrictEqual(r.s1, new Uint8Array([102, 111, 111]));
    assert.deepStrictEqual(r.s2, new Uint8Array([98, 97, 114]));
    assert.deepStrictEqual(r.s3, new Uint8Array([124, 98, 97, 122, 64]));
  });
});
