// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('DefaultEndianExprException', () => {
  it('parses test properly', async () => {
    const { DefaultEndianExprException } = await import('../compiled/testformats/DefaultEndianExprException.js');
    const io = new KaitaiStream(fs.readFileSync('src/endian_expr.bin'));
    assert.ok(KaitaiStream.UndecidedEndiannessError);
    assert.throws(() => new DefaultEndianExprException(io), KaitaiStream.UndecidedEndiannessError);
  });
});
