// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatEosBitsB1', () => {
  it('parses test properly', async () => {
    const { RepeatEosBitsB1 } = await import('../compiled/RepeatEosBitsB1.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new RepeatEosBitsB1(io);
    assert.strictEqual(r.bits.length, 16);
    assert.strictEqual(r.bits[0], true);
    assert.strictEqual(r.bits[1], true);
    assert.strictEqual(r.bits[2], true);
    assert.strictEqual(r.bits[3], true);
    assert.strictEqual(r.bits[4], true);
    assert.strictEqual(r.bits[5], true);
    assert.strictEqual(r.bits[6], true);
    assert.strictEqual(r.bits[7], true);
    assert.strictEqual(r.bits[8], false);
    assert.strictEqual(r.bits[9], false);
    assert.strictEqual(r.bits[10], false);
    assert.strictEqual(r.bits[11], false);
    assert.strictEqual(r.bits[12], false);
    assert.strictEqual(r.bits[13], false);
    assert.strictEqual(r.bits[14], false);
    assert.strictEqual(r.bits[15], true);
  });
});
