// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EofExceptionSized', () => {
  it('parses test properly', async () => {
    const { EofExceptionSized } = await import('#testformats/EofExceptionSized.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    assert.ok(KaitaiStream.EOFError);
    assert.throws(() => new EofExceptionSized(io), KaitaiStream.EOFError);
  });
});
