// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailRangeStr', () => {
  it('parses test properly', async () => {
    const { ValidFailRangeStr } = await import('../compiled/testformats/ValidFailRangeStr.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    assert.ok(KaitaiStream.ValidationGreaterThanError);
    assert.throws(() => new ValidFailRangeStr(io), KaitaiStream.ValidationGreaterThanError);
  });
});
