// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprArray', () => {
  it('parses test properly', async () => {
    const { ExprArray } = await import('#testformats/ExprArray.js');
    const io = new KaitaiStream(fs.readFileSync('src/expr_array.bin'));
    const r = new ExprArray(io);
    assert.strictEqual(r.aintSize, 4);
    assert.strictEqual(r.aintFirst, 7657765);
    assert.strictEqual(r.aintLast, 16272640);
    assert.strictEqual(r.aintMin, 49185);
    assert.strictEqual(r.aintMax, 1123362332);
    assert.strictEqual(r.afloatSize, 3);
    assert(Math.abs(r.afloatFirst - -2.6839530254859364E-121) < 1e-6);
    assert(Math.abs(r.afloatLast - -1.1103359815095273E-175) < 1e-6);
    assert(Math.abs(r.afloatMin - -8.754689149998834E+288) < 1e-6);
    assert(Math.abs(r.afloatMax - -1.1103359815095273E-175) < 1e-6);
    assert.strictEqual(r.astrSize, 3);
    assert.strictEqual(r.astrFirst, "foo");
    assert.strictEqual(r.astrLast, "baz");
    assert.strictEqual(r.astrMin, "bar");
    assert.strictEqual(r.astrMax, "foo");
  });
});
