// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchIntegers', () => {
  it('parses test properly', async () => {
    const { SwitchIntegers } = await import('#testformats/SwitchIntegers.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_integers.bin'));
    const r = new SwitchIntegers(io);
    assert.strictEqual(r.opcodes.length, 4);
    assert.strictEqual(r.opcodes[0].code, 1);
    assert.strictEqual(r.opcodes[0].body, 7);
    assert.strictEqual(r.opcodes[1].code, 2);
    assert.strictEqual(r.opcodes[1].body, 16448);
    assert.strictEqual(r.opcodes[2].code, 4);
    assert.strictEqual(r.opcodes[2].body, 4919);
    assert.strictEqual(r.opcodes[3].code, 8);
    assert.strictEqual(r.opcodes[3].body, 4919);
  });
});
