// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprCalcArrayOps', () => {
  it('parses test properly', async () => {
    const { ExprCalcArrayOps } = await import('../compiled/ExprCalcArrayOps.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ExprCalcArrayOps(io);
    assert.strictEqual(r.intArraySize, 7);
    assert.strictEqual(r.intArrayFirst, 10);
    assert.strictEqual(r.intArrayMid, 25);
    assert.strictEqual(r.intArrayLast, 1000);
    assert.strictEqual(r.intArrayMin, 10);
    assert.strictEqual(r.intArrayMax, 1000);
    assert.strictEqual(r.doubleArraySize, 5);
    assert(Math.abs(r.doubleArrayFirst - 10.0) < 1e-6);
    assert(Math.abs(r.doubleArrayMid - 25.0) < 1e-6);
    assert(Math.abs(r.doubleArrayLast - 3.14159) < 1e-6);
    assert(Math.abs(r.doubleArrayMin - 3.14159) < 1e-6);
    assert(Math.abs(r.doubleArrayMax - 100.0) < 1e-6);
    assert.strictEqual(r.strArraySize, 4);
    assert.strictEqual(r.strArrayFirst, "un");
    assert.strictEqual(r.strArrayMid, "deux");
    assert.strictEqual(r.strArrayLast, "quatre");
    assert.strictEqual(r.strArrayMin, "deux");
    assert.strictEqual(r.strArrayMax, "un");
  });
});
