// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('PositionInSeq', () => {
  it('parses test properly', async () => {
    const { PositionInSeq } = await import('#testformats/PositionInSeq.js');
    const io = new KaitaiStream(fs.readFileSync('src/position_in_seq.bin'));
    const r = new PositionInSeq(io);
    assert.deepStrictEqual(r.numbers, [0 + 1, 2, 3]);
  });
});
