// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StrEncodingsUtf16', () => {
  it('parses test properly', async () => {
    const { StrEncodingsUtf16 } = await import('#testformats/StrEncodingsUtf16.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_encodings_utf16.bin'));
    const r = new StrEncodingsUtf16(io);
    assert.strictEqual(r.lenBe, 12);
    assert.strictEqual(r.beBomRemoved.bom, 65279);
    assert.strictEqual(r.beBomRemoved.str, "\u3053\u3093\u306b\u3061\u306f");
    assert.strictEqual(r.lenLe, 12);
    assert.strictEqual(r.leBomRemoved.bom, 65279);
    assert.strictEqual(r.leBomRemoved.str, "\u3053\u3093\u306b\u3061\u306f");
  });
});
