// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchElseOnly', () => {
  it('parses test properly', async () => {
    const { SwitchElseOnly } = await import('#testformats/SwitchElseOnly.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_opcodes.bin'));
    const r = new SwitchElseOnly(io);
    assert.strictEqual(r.opcode, 83);
    assert.strictEqual(r.primByte, 102);
    assert.deepStrictEqual(r.ut.value, new Uint8Array([114, 0, 73, 66]));
  });
});
