// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('TermStrzUtf16V2', () => {
  it('parses test properly', async () => {
    const { TermStrzUtf16V2 } = await import('../compiled/testformats/TermStrzUtf16V2.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz_utf16.bin'));
    const r = new TermStrzUtf16V2(io);
    assert.strictEqual(r.s1, "a\u0200b");
    assert.strictEqual(r.s2, "c\u0200d\x00");
    assert.strictEqual(r.s3, "e\u0200f");
  });
});
