// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessCoerceBytes', () => {
  it('parses test properly', async () => {
    const { ProcessCoerceBytes } = await import('../compiled/testformats/ProcessCoerceBytes.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_coerce_bytes.bin'));
    const r = new ProcessCoerceBytes(io);
    assert.strictEqual(r.records[0].flag, 0);
    assert.deepStrictEqual(r.records[0].buf, new Uint8Array([65, 65, 65, 65]));
    assert.strictEqual(r.records[1].flag, 1);
    assert.deepStrictEqual(r.records[1].buf, new Uint8Array([66, 66, 66, 66]));
  });
});
