// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('TermStrz3', () => {
  it('parses test properly', async () => {
    const { TermStrz3 } = await import('../compiled/testformats/TermStrz3.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TermStrz3(io);
    assert.strictEqual(r.s1, "foo");
    assert.strictEqual(r.s2, "|bar|baz");
    assert.strictEqual(r.s3, "");
  });
});
