// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatNStruct', () => {
  it('parses test properly', async () => {
    const { RepeatNStruct } = await import('../compiled/testformats/RepeatNStruct.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_n_struct.bin'));
    const r = new RepeatNStruct(io);
    assert.strictEqual(r.chunks.length, 2);
    assert.strictEqual(r.chunks[0].offset, 16);
    assert.strictEqual(r.chunks[0].len, 8312);
    assert.strictEqual(r.chunks[1].offset, 8328);
    assert.strictEqual(r.chunks[1].len, 15);
  });
});
