// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumIntRangeS', () => {
  it('parses test properly', async () => {
    const { EnumIntRangeS } = await import('../compiled/testformats/EnumIntRangeS.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_int_range_s.bin'));
    const r = new EnumIntRangeS(io);
    assert.strictEqual(r.f1, EnumIntRangeS.Constants.INT_MIN);
    assert.strictEqual(r.f2, EnumIntRangeS.Constants.ZERO);
    assert.strictEqual(r.f3, EnumIntRangeS.Constants.INT_MAX);
  });
});
