// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('EosExceptionBytes', () => {
  it('parses test properly', async () => {
    const { EosExceptionBytes } = await import('../compiled/testformats/EosExceptionBytes.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    assert.ok(KaitaiStream.EOFError);
    assert.throws(() => new EosExceptionBytes(io), KaitaiStream.EOFError);
  });
});
