// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('TsPacketHeader', () => {
  it('parses test properly', async () => {
    const { TsPacketHeader } = await import('#testformats/TsPacketHeader.js');
    const io = new KaitaiStream(fs.readFileSync('src/ts_packet.bin'));
    const r = new TsPacketHeader(io);
    assert.strictEqual(r.syncByte, 71);
    assert.strictEqual(r.transportErrorIndicator, false);
    assert.strictEqual(r.payloadUnitStartIndicator, false);
    assert.strictEqual(r.transportPriority, true);
    assert.strictEqual(r.pid, 33);
    assert.strictEqual(r.transportScramblingControl, 0);
    assert.strictEqual(r.adaptationFieldControl, TsPacketHeader.AdaptationFieldControlEnum.PAYLOAD_ONLY);
  });
});
