// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ImportsParamsDefUsertypeImported', () => {
  it('parses test properly', async () => {
    const { ImportsParamsDefUsertypeImported } = await import('../compiled/testformats/ImportsParamsDefUsertypeImported.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new ImportsParamsDefUsertypeImported(io);
    assert.strictEqual(r.hw.one, 236);
    assert.strictEqual(r.two.hwOne, 236);
  });
});
