// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('StrPadTermRoundtrip', () => {
  it('parses test properly', async () => {
    const { StrPadTermRoundtrip } = await import('../compiled/testformats/StrPadTermRoundtrip.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term.bin'));
    const r = new StrPadTermRoundtrip(io);
    assert.strictEqual(r.strPad, "str1");
    assert.strictEqual(r.strTerm, "str2foo");
    assert.strictEqual(r.strTermAndPad, "str+++3bar+++");
    assert.strictEqual(r.strTermInclude, "str4baz@");
  });
});
