// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsPassArrayIo', () => {
  it('parses test properly', async () => {
    const { ParamsPassArrayIo } = await import('#testformats/ParamsPassArrayIo.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new ParamsPassArrayIo(io);
    assert.strictEqual(r.first.foo, 255);
    assert.deepStrictEqual(r.one.buf, new Uint8Array([1]));
  });
});
