// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NavParentFalse', () => {
  it('parses test properly', async () => {
    const { NavParentFalse } = await import('#testformats/NavParentFalse.js');
    const io = new KaitaiStream(fs.readFileSync('src/nav_parent_codes.bin'));
    const r = new NavParentFalse(io);
    assert.strictEqual(r.childSize, 3);
    assert.strictEqual(r.elementA.foo.code, 73);
    assert.deepStrictEqual(r.elementA.foo.more, new Uint8Array([49, 50, 51]));
    assert.strictEqual(r.elementA.bar.foo.code, 66);
    assert.strictEqual(r.elementB.foo.code, 98);
  });
});
