// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailRangeFloat', () => {
  it('parses test properly', async () => {
    const { ValidFailRangeFloat } = await import('#testformats/ValidFailRangeFloat.js');
    const io = new KaitaiStream(fs.readFileSync('src/floating_points.bin'));
    assert.ok(KaitaiStream.ValidationGreaterThanError);
    assert.throws(() => new ValidFailRangeFloat(io), KaitaiStream.ValidationGreaterThanError);
  });
});
