// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NameClashImportVsInst', () => {
  it('parses test properly', async () => {
    const { NameClashImportVsInst } = await import('#testformats/NameClashImportVsInst.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new NameClashImportVsInst(io);
    assert.strictEqual(r.integers.uint8, 255);
    assert.strictEqual(r.std, 3);
  });
});
