// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailRepeatAnyofInt', () => {
  it('parses test properly', async () => {
    const { ValidFailRepeatAnyofInt } = await import('../compiled/testformats/ValidFailRepeatAnyofInt.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_coerce_bytes.bin'));
    assert.ok(KaitaiStream.ValidationNotAnyOfError);
    assert.throws(() => new ValidFailRepeatAnyofInt(io), KaitaiStream.ValidationNotAnyOfError);
  });
});
