// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('NestedTypeParam', () => {
  it('parses test properly', async () => {
    const { NestedTypeParam } = await import('#testformats/NestedTypeParam.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new NestedTypeParam(io);
    assert.strictEqual(r.mainSeq.myLen, 5);
    assert.strictEqual(r.mainSeq.body, "foo|b");
  });
});
