// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessXorConst', () => {
  it('parses test properly', async () => {
    const { ProcessXorConst } = await import('../compiled/ProcessXorConst.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_1.bin'));
    const r = new ProcessXorConst(io);
    assert.strictEqual(r.key, 255);
    assert.deepStrictEqual(r.buf, new Uint8Array([102, 111, 111, 32, 98, 97, 114]));
  });
});
