// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ImportsParamsDefEnumImported', () => {
  it('parses test properly', async () => {
    const { ImportsParamsDefEnumImported } = await import('#testformats/ImportsParamsDefEnumImported.js');
    const { Enum0 } = await import('#testformats/Enum0.js');
    const { EnumDeep } = await import('#testformats/EnumDeep.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new ImportsParamsDefEnumImported(io);
    assert.strictEqual(r.one.pet1, Enum0.Animal.CAT);
    assert.strictEqual(r.one.pet2, EnumDeep.Container1.Container2.Animal.HARE);
    assert.strictEqual(r.two.pet1Param, Enum0.Animal.CAT);
    assert.strictEqual(r.two.pet2Param, EnumDeep.Container1.Container2.Animal.HARE);
  });
});
