// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsEnum', () => {
  it('parses test properly', async () => {
    const { BitsEnum } = await import('#testformats/BitsEnum.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new BitsEnum(io);
    assert.strictEqual(r.one, BitsEnum.Animal.PLATYPUS);
    assert.strictEqual(r.two, BitsEnum.Animal.HORSE);
    assert.strictEqual(r.three, BitsEnum.Animal.CAT);
  });
});
