// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailRepeatExpr', () => {
  it('parses test properly', async () => {
    const { ValidFailRepeatExpr } = await import('#testformats/ValidFailRepeatExpr.js');
    const io = new KaitaiStream(fs.readFileSync('src/bcd_user_type_be.bin'));
    assert.ok(KaitaiStream.ValidationExprError);
    assert.throws(() => new ValidFailRepeatExpr(io), KaitaiStream.ValidationExprError);
  });
});
