// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprIntDiv', () => {
  it('parses test properly', async () => {
    const { ExprIntDiv } = await import('../compiled/ExprIntDiv.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ExprIntDiv(io);
    assert.strictEqual(r.intU, 1262698832);
    assert.strictEqual(r.intS, -52947);
    assert.strictEqual(r.divPosConst, 756);
    assert.strictEqual(r.divNegConst, -757);
    assert.strictEqual(r.divPosSeq, 97130679);
    assert.strictEqual(r.divNegSeq, -4073);
  });
});
