// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprSizeofValue0', () => {
  it('parses test properly', async () => {
    const { ExprSizeofValue0 } = await import('../compiled/ExprSizeofValue0.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ExprSizeofValue0(io);
    assert.strictEqual(r.selfSizeof, ((1 + 4) + 2) + 2);
    assert.strictEqual(r.sizeofBlock, (1 + 4) + 2);
    assert.strictEqual(r.sizeofBlockA, 1);
    assert.strictEqual(r.sizeofBlockB, 4);
    assert.strictEqual(r.sizeofBlockC, 2);
  });
});
