// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('NonStandard', () => {
  it('parses test properly', async () => {
    const { NonStandard } = await import('../compiled/testformats/NonStandard.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new NonStandard(io);
    assert.strictEqual(r.foo, 80);
  });
});
