// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessCoerceSwitch', () => {
  it('parses test properly', async () => {
    const { ProcessCoerceSwitch } = await import('../compiled/testformats/ProcessCoerceSwitch.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_coerce_switch.bin'));
    const r = new ProcessCoerceSwitch(io);
    assert.strictEqual(r.bufType, 0);
    assert.strictEqual(r.flag, 0);
    assert.deepStrictEqual(r.buf.bar, new Uint8Array([65, 65, 65, 65]));
  });
});
