// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('TermBytes3', () => {
  it('parses test properly', async () => {
    const { TermBytes3 } = await import('#testformats/TermBytes3.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TermBytes3(io);
    assert.deepStrictEqual(r.s1, new Uint8Array([102, 111, 111]));
    assert.deepStrictEqual(r.s2, new Uint8Array([124, 98, 97, 114, 124, 98, 97, 122]));
    assert.deepStrictEqual(r.s3, new Uint8Array([]));
  });
});
