// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessRepeatUsertypeDynargXor', () => {
  it('parses test properly', async () => {
    const { ProcessRepeatUsertypeDynargXor } = await import('#testformats/ProcessRepeatUsertypeDynargXor.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new ProcessRepeatUsertypeDynargXor(io);
    assert.strictEqual(r.blocks[0].a, 2319263090);
    assert.strictEqual(r.blocks[1].a, 263540053);
    assert.strictEqual(r.blocksB.dummy, 209);
    assert.strictEqual(r.blocksB.blocks0B, 20);
    assert.strictEqual(r.blocksB.blocks1B, 91);
  });
});
