// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidEqStrEncodings', () => {
  it('parses test properly', async () => {
    const { ValidEqStrEncodings } = await import('../compiled/ValidEqStrEncodings.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_encodings.bin'));
    const r = new ValidEqStrEncodings(io);
  });
});
