// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('BytesPadTermZeroSize', () => {
  it('parses test properly', async () => {
    const { BytesPadTermZeroSize } = await import('#testformats/BytesPadTermZeroSize.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new BytesPadTermZeroSize(io);
    assert.deepStrictEqual(r.strPad, new Uint8Array([]));
    assert.deepStrictEqual(r.strTerm, new Uint8Array([]));
    assert.deepStrictEqual(r.strTermAndPad, new Uint8Array([]));
    assert.deepStrictEqual(r.strTermInclude, new Uint8Array([]));
  });
});
