// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumImportLiterals', () => {
  it('parses test properly', async () => {
    const { EnumImportLiterals } = await import('../compiled/testformats/EnumImportLiterals.js');
    const { EnumDeep } = await import('../compiled/testformats/EnumDeep.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new EnumImportLiterals(io);
    assert.strictEqual(r.pet1ToI, 7);
    assert.strictEqual(r.pet1Eq, true);
    assert.strictEqual(r.pet2, EnumDeep.Container1.Container2.Animal.HARE);
  });
});
