// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidNotParsedIf', () => {
  it('parses test properly', async () => {
    const { ValidNotParsedIf } = await import('../compiled/ValidNotParsedIf.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ValidNotParsedIf(io);
  });
});
