// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StrPadTermZeroSize', () => {
  it('parses test properly', async () => {
    const { StrPadTermZeroSize } = await import('#testformats/StrPadTermZeroSize.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new StrPadTermZeroSize(io);
    assert.strictEqual(r.strPad, "");
    assert.strictEqual(r.strTerm, "");
    assert.strictEqual(r.strTermAndPad, "");
    assert.strictEqual(r.strTermInclude, "");
  });
});
