// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('IndexSizes', () => {
  it('parses test properly', async () => {
    const { IndexSizes } = await import('../compiled/testformats/IndexSizes.js');
    const io = new KaitaiStream(fs.readFileSync('src/index_sizes.bin'));
    const r = new IndexSizes(io);
    assert.strictEqual(r.qty, 3);
    assert.strictEqual(r.sizes[0], 1);
    assert.strictEqual(r.sizes[1], 8);
    assert.strictEqual(r.sizes[2], 4);
    assert.strictEqual(r.bufs[0], "A");
    assert.strictEqual(r.bufs[1], "BBBBBBBB");
    assert.strictEqual(r.bufs[2], "CCCC");
  });
});
