// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumLongRangeU', () => {
  it('parses test properly', async () => {
    const { EnumLongRangeU } = await import('../compiled/EnumLongRangeU.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_long_range_u.bin'));
    const r = new EnumLongRangeU(io);
    assert.strictEqual(r.f1, EnumLongRangeU.Constants.ZERO);
    assert.strictEqual(r.f2, EnumLongRangeU.Constants.INT_MAX);
    assert.strictEqual(r.f3, EnumLongRangeU.Constants.INT_OVER_MAX);
    assert.strictEqual(r.f4, EnumLongRangeU.Constants.LONG_MAX);
  });
});
