// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('IfStruct', () => {
  it('parses test properly', async () => {
    const { IfStruct } = await import('../compiled/IfStruct.js');
    const io = new KaitaiStream(fs.readFileSync('src/if_struct.bin'));
    const r = new IfStruct(io);
    assert.strictEqual(r.op1.opcode, 83);
    assert.strictEqual(r.op1.argTuple, undefined);
    assert.strictEqual(r.op1.argStr.str, "foo");
    assert.strictEqual(r.op2.opcode, 84);
    assert.strictEqual(r.op2.argTuple.num1, 66);
    assert.strictEqual(r.op2.argTuple.num2, 67);
    assert.strictEqual(r.op2.argStr, undefined);
    assert.strictEqual(r.op3.opcode, 83);
    assert.strictEqual(r.op3.argTuple, undefined);
    assert.strictEqual(r.op3.argStr.str, "bar");
  });
});
