// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('InstanceInRepeatUntil', () => {
  it('parses test properly', async () => {
    const { InstanceInRepeatUntil } = await import('../compiled/testformats/InstanceInRepeatUntil.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_until_s4.bin'));
    const r = new InstanceInRepeatUntil(io);
    assert.strictEqual(r.entries.length, 5);
    assert.strictEqual(r.entries[0], 66);
    assert.strictEqual(r.entries[1], 0);
    assert.strictEqual(r.entries[2], 4919);
    assert.strictEqual(r.entries[3], 0);
    assert.strictEqual(r.entries[4], -1);
  });
});
