// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('InstanceInSized', () => {
  it('parses test properly', async () => {
    const { InstanceInSized } = await import('#testformats/InstanceInSized.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_rotate.bin'));
    const r = new InstanceInSized(io);
    assert.strictEqual(r.cont.seqSized.seqF, 9);
    assert.strictEqual(r.cont.seqSized.instInvoked, 172);
    assert.deepStrictEqual(r.cont.seqSized.instUnusedBySeq, new Uint8Array([141, 141]));
    assert.strictEqual(r.cont.seqInStream.seqF, 237);
    assert.deepStrictEqual(r.cont.seqInStream.inst, new Uint8Array([186, 123, 147]));
    assert.strictEqual(r.cont.instInStream.seqF, 99);
    assert.deepStrictEqual(r.cont.instInStream.inst, new Uint8Array([35, 1, 42]));
    assert.strictEqual(r.cont.instSized.seqF, 52);
    assert.strictEqual(r.cont.instSized.instInvoked, 178);
    assert.deepStrictEqual(r.cont.instSized.instUnusedBySeq, new Uint8Array([57, 178]));
  });
});
