// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('InstanceUserArray', () => {
  it('parses test properly', async () => {
    const { InstanceUserArray } = await import('../compiled/InstanceUserArray.js');
    const io = new KaitaiStream(fs.readFileSync('src/instance_std_array.bin'));
    const r = new InstanceUserArray(io);
    assert.strictEqual(r.ofs, 16);
    assert.strictEqual(r.qtyEntries, 3);
    assert.strictEqual(r.entrySize, 4);
    assert.strictEqual(r.userEntries.length, 3);
    assert.strictEqual(r.userEntries[0].word1, 4369);
    assert.strictEqual(r.userEntries[0].word2, 4369);
    assert.strictEqual(r.userEntries[1].word1, 8738);
    assert.strictEqual(r.userEntries[1].word2, 8738);
    assert.strictEqual(r.userEntries[2].word1, 13107);
    assert.strictEqual(r.userEntries[2].word2, 13107);
  });
});
