// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprSizeofValueSized', () => {
  it('parses test properly', async () => {
    const { ExprSizeofValueSized } = await import('../compiled/ExprSizeofValueSized.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ExprSizeofValueSized(io);
    assert.strictEqual(r.selfSizeof, 12 + 2);
    assert.strictEqual(r.sizeofBlock, 12);
    assert.strictEqual(r.sizeofBlockA, 1);
    assert.strictEqual(r.sizeofBlockB, 4);
    assert.strictEqual(r.sizeofBlockC, 2);
  });
});
