// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumIf', () => {
  it('parses test properly', async () => {
    const { EnumIf } = await import('#testformats/EnumIf.js');
    const io = new KaitaiStream(fs.readFileSync('src/if_struct.bin'));
    const r = new EnumIf(io);
    assert.strictEqual(r.op1.opcode, EnumIf.Opcodes.A_STRING);
    assert.strictEqual(r.op1.argStr.str, "foo");
    assert.strictEqual(r.op2.opcode, EnumIf.Opcodes.A_TUPLE);
    assert.strictEqual(r.op2.argTuple.num1, 66);
    assert.strictEqual(r.op2.argTuple.num2, 67);
    assert.strictEqual(r.op3.opcode, EnumIf.Opcodes.A_STRING);
    assert.strictEqual(r.op3.argStr.str, "bar");
  });
});
