// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessCoerceUsertype1', () => {
  it('parses test properly', async () => {
    const { ProcessCoerceUsertype1 } = await import('#testformats/ProcessCoerceUsertype1.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_coerce_bytes.bin'));
    const r = new ProcessCoerceUsertype1(io);
    assert.strictEqual(r.records[0].flag, 0);
    assert.strictEqual(r.records[0].buf.value, 1094795585);
    assert.strictEqual(r.records[1].flag, 1);
    assert.strictEqual(r.records[1].buf.value, 1111638594);
  });
});
