// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ImportsCastToImported2', () => {
  it('parses test properly', async () => {
    const { ImportsCastToImported2 } = await import('../compiled/testformats/ImportsCastToImported2.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_xor_4.bin'));
    const r = new ImportsCastToImported2(io);
    assert.strictEqual(r.hw.one, 236);
    assert.strictEqual(r.two.hw.one, 236);
  });
});
