// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('TypeTernaryOpaque', () => {
  it('parses test properly', async () => {
    const { TypeTernaryOpaque } = await import('../compiled/TypeTernaryOpaque.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TypeTernaryOpaque(io);
    assert.strictEqual(r.dif.one, 102);
  });
});
