// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidLong', () => {
  it('parses test properly', async () => {
    const { ValidLong } = await import('../compiled/testformats/ValidLong.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ValidLong(io);
  });
});
