// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ParamsPassArrayUsertype', () => {
  it('parses test properly', async () => {
    const { ParamsPassArrayUsertype } = await import('#testformats/ParamsPassArrayUsertype.js');
    const io = new KaitaiStream(fs.readFileSync('src/position_to_end.bin'));
    const r = new ParamsPassArrayUsertype(io);
    assert.strictEqual(r.passBlocks.bar.length, 2);
    assert.strictEqual(r.passBlocks.bar[0].foo, 1);
    assert.strictEqual(r.passBlocks.bar[1].foo, 2);
    assert.deepStrictEqual(r.passBlocks.one, new Uint8Array([3]));
    assert.deepStrictEqual(r.passBlocks.two, new Uint8Array([4, 5]));
  });
});
