// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('BitsShiftByB32Le', () => {
  it('parses test properly', async () => {
    const { BitsShiftByB32Le } = await import('../compiled/testformats/BitsShiftByB32Le.js');
    const io = new KaitaiStream(fs.readFileSync('src/bits_shift_by_b32_le.bin'));
    const r = new BitsShiftByB32Le(io);
    assert.strictEqual(r.a, 4294967295);
    assert.strictEqual(r.b, 0);
  });
});
