// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('CombineBytes', () => {
  it('parses test properly', async () => {
    const { CombineBytes } = await import('../compiled/CombineBytes.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new CombineBytes(io);
    assert.deepStrictEqual(r.bytesTerm, new Uint8Array([102, 111, 111]));
    assert.deepStrictEqual(r.bytesLimit, new Uint8Array([98, 97, 114, 124]));
    assert.deepStrictEqual(r.bytesEos, new Uint8Array([98, 97, 122, 64]));
    assert.deepStrictEqual(r.bytesCalc, new Uint8Array([82, 110, 68]));
    assert.deepStrictEqual(r.termOrLimit, new Uint8Array([102, 111, 111]));
    assert.deepStrictEqual(r.termOrEos, new Uint8Array([98, 97, 122, 64]));
    assert.deepStrictEqual(r.termOrCalc, new Uint8Array([102, 111, 111]));
    assert.deepStrictEqual(r.limitOrEos, new Uint8Array([98, 97, 114, 124]));
    assert.deepStrictEqual(r.limitOrCalc, new Uint8Array([82, 110, 68]));
    assert.deepStrictEqual(r.eosOrCalc, new Uint8Array([98, 97, 122, 64]));
  });
});
