// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('NavParentSwitch', () => {
  it('parses test properly', async () => {
    const { NavParentSwitch } = await import('../compiled/testformats/NavParentSwitch.js');
    const io = new KaitaiStream(fs.readFileSync('src/nav_parent_switch.bin'));
    const r = new NavParentSwitch(io);
    assert.strictEqual(r.category, 1);
    assert.strictEqual(r.content.foo, 66);
    assert.strictEqual(r.content.subelement.bar, 255);
  });
});
