// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('TermStruct4', () => {
  it('parses test properly', async () => {
    const { TermStruct4 } = await import('../compiled/TermStruct4.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TermStruct4(io);
    assert.deepStrictEqual(r.s1.value.value, new Uint8Array([102, 111, 111]));
    assert.deepStrictEqual(r.s2.value.value, new Uint8Array([98, 97, 114]));
    assert.deepStrictEqual(r.s3.value.value, new Uint8Array([98, 97, 122]));
  });
});
