// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StrEncodingsDefault', () => {
  it('parses test properly', async () => {
    const { StrEncodingsDefault } = await import('#testformats/StrEncodingsDefault.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_encodings.bin'));
    const r = new StrEncodingsDefault(io);
    assert.strictEqual(r.str1, "Some ASCII");
    assert.strictEqual(r.rest.str2, "\u3053\u3093\u306b\u3061\u306f");
    assert.strictEqual(r.rest.str3, "\u3053\u3093\u306b\u3061\u306f");
    assert.strictEqual(r.rest.str4, "\u2591\u2592\u2593");
  });
});
