// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatUntilS4', () => {
  it('parses test properly', async () => {
    const { RepeatUntilS4 } = await import('../compiled/RepeatUntilS4.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_until_s4.bin'));
    const r = new RepeatUntilS4(io);
    assert.deepStrictEqual(r.entries, [66, 4919, -251658241, -1]);
    assert.strictEqual(r.afterall, "foobar");
  });
});
