// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('StrEosPadTermEmpty', () => {
  it('parses test properly', async () => {
    const { StrEosPadTermEmpty } = await import('#testformats/StrEosPadTermEmpty.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_pad_term_empty.bin'));
    const r = new StrEosPadTermEmpty(io);
    assert.strictEqual(r.strPad.value, "");
    assert.strictEqual(r.strTerm.value, "");
    assert.strictEqual(r.strTermAndPad.value, "");
    assert.strictEqual(r.strTermInclude.value, "@");
  });
});
