// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('SwitchIntegers2', () => {
  it('parses test properly', async () => {
    const { SwitchIntegers2 } = await import('../compiled/testformats/SwitchIntegers2.js');
    const io = new KaitaiStream(fs.readFileSync('src/switch_integers.bin'));
    const r = new SwitchIntegers2(io);
    assert.strictEqual(r.code, 1);
    assert.strictEqual(r.len, 7);
    assert.deepStrictEqual(r.ham, new Uint8Array([2, 64, 64, 4, 55, 19, 0]));
    assert.strictEqual(r.padding, 0);
    assert.strictEqual(r.lenModStr, "13");
  });
});
