// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ValidFailRepeatInst', () => {
  it('parses test properly', async () => {
    const { ValidFailRepeatInst } = await import('#testformats/ValidFailRepeatInst.js');
    const io = new KaitaiStream(fs.readFileSync('src/bcd_user_type_be.bin'));
    assert.ok(KaitaiStream.ValidationNotEqualError);
    assert.throws(() => new ValidFailRepeatInst(io), KaitaiStream.ValidationNotEqualError);
  });
});
