// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('IntegersDoubleOverflow', () => {
  it('parses test properly', async () => {
    const { IntegersDoubleOverflow } = await import('#testformats/IntegersDoubleOverflow.js');
    const io = new KaitaiStream(fs.readFileSync('src/integers_double_overflow.bin'));
    const r = new IntegersDoubleOverflow(io);
    assert.strictEqual(r.signedSafeMinBe, -9007199254740991);
    assert.strictEqual(r.signedSafeMinLe, -9007199254740991);
    assert.strictEqual(r.signedSafeMaxBe, 9007199254740991);
    assert.strictEqual(r.signedSafeMaxLe, 9007199254740991);
    assert.strictEqual((r.signedUnsafeNegBe).toString(), "-9007199254740993");
    assert.strictEqual((r.signedUnsafeNegLe).toString(), "-9007199254740993");
    assert.strictEqual((r.signedUnsafePosBe).toString(), "9007199254740993");
    assert.strictEqual((r.signedUnsafePosBe).toString(), "9007199254740993");
  });
});
