// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('Expr2', () => {
  it('parses test properly', async () => {
    const { Expr2 } = await import('../compiled/testformats/Expr2.js');
    const io = new KaitaiStream(fs.readFileSync('src/str_encodings.bin'));
    const r = new Expr2(io);
    assert.strictEqual(r.str1.lenOrig, 10);
    assert.strictEqual(r.str1.lenMod, 7);
    assert.strictEqual(r.str1.str, "Some AS");
    assert.strictEqual(r.str1Len, 7);
    assert.strictEqual(r.str1LenMod, 7);
    assert.strictEqual(r.str1Byte1, 73);
    assert.strictEqual(r.str1Avg, 73);
    assert.strictEqual(r.str1Char5, "e");
    assert.strictEqual(r.str1Tuple5.byte0, 101);
    assert.strictEqual(r.str1Tuple5.byte0, 101);
    assert.strictEqual(r.str1Tuple5.byte1, 32);
    assert.strictEqual(r.str1Tuple5.byte2, 65);
    assert.strictEqual(r.str1Tuple5.avg, 48);
    assert.strictEqual(r.str2Tuple5.byte0, 101);
    assert.strictEqual(r.str2Tuple5.byte1, 32);
    assert.strictEqual(r.str2Tuple5.byte2, 65);
    assert.strictEqual(r.str2Tuple5.avg, 48);
  });
});
