// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('OpaqueExternalType', () => {
  it('parses test properly', async () => {
    const { OpaqueExternalType } = await import('../compiled/OpaqueExternalType.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new OpaqueExternalType(io);
    assert.strictEqual(r.hw.one, 102);
  });
});
