// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ProcessCustomNoArgs', () => {
  it('parses test properly', async () => {
    const { ProcessCustomNoArgs } = await import('../compiled/ProcessCustomNoArgs.js');
    const io = new KaitaiStream(fs.readFileSync('src/process_rotate.bin'));
    const r = new ProcessCustomNoArgs(io);
    assert.deepStrictEqual(r.buf, new Uint8Array([95, 9, 172, 141, 141, 237, 95]));
  });
});
