// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprBytesNonLiteral', () => {
  it('parses test properly', async () => {
    const { ExprBytesNonLiteral } = await import('#testformats/ExprBytesNonLiteral.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_negative.bin'));
    const r = new ExprBytesNonLiteral(io);
    assert.strictEqual(r.calcBytes.length, 2);
    assert.strictEqual(r.calcBytes[0], 255);
    assert.strictEqual(r.calcBytes[1], 1);
  });
});
