// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('ExprIoEof', () => {
  it('parses test properly', async () => {
    const { ExprIoEof } = await import('#testformats/ExprIoEof.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new ExprIoEof(io);
    assert.strictEqual(r.substream1.one, 1262698832);
    assert.strictEqual(r.substream1.two, undefined);
    assert.strictEqual(r.substream2.one, 4294914349);
    assert.strictEqual(r.substream2.two, 1262698832);
  });
});
