// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('MultipleUse', () => {
  it('parses test properly', async () => {
    const { MultipleUse } = await import('#testformats/MultipleUse.js');
    const io = new KaitaiStream(fs.readFileSync('src/position_abs.bin'));
    const r = new MultipleUse(io);
    assert.strictEqual(r.t1.firstUse.value, 32);
    assert.strictEqual(r.t2.secondUse.value, 32);
  });
});
