// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('RepeatEosU4', () => {
  it('parses test properly', async () => {
    const { RepeatEosU4 } = await import('#testformats/RepeatEosU4.js');
    const io = new KaitaiStream(fs.readFileSync('src/repeat_eos_struct.bin'));
    const r = new RepeatEosU4(io);
    assert.strictEqual(r.numbers.length, 4);
    assert.strictEqual(r.numbers[0], 0);
    assert.strictEqual(r.numbers[1], 66);
    assert.strictEqual(r.numbers[2], 66);
    assert.strictEqual(r.numbers[3], 2069);
  });
});
