// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert';
import { KaitaiStream } from 'kaitai-struct';

describe('TypeTernary', () => {
  it('parses test properly', async () => {
    const { TypeTernary } = await import('../compiled/testformats/TypeTernary.js');
    const io = new KaitaiStream(fs.readFileSync('src/term_strz.bin'));
    const r = new TypeTernary(io);
    assert.strictEqual(r.dif.value, 101);
  });
});
