// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('IfValues', () => {
  it('parses test properly', async () => {
    const { IfValues } = await import('#testformats/IfValues.js');
    const io = new KaitaiStream(fs.readFileSync('src/fixed_struct.bin'));
    const r = new IfValues(io);
    assert.strictEqual(r.codes[0].opcode, 80);
    assert.strictEqual(r.codes[0].halfOpcode, 40);
    assert.strictEqual(r.codes[1].opcode, 65);
    assert.strictEqual(r.codes[1].halfOpcode, undefined);
    assert.strictEqual(r.codes[2].opcode, 67);
    assert.strictEqual(r.codes[2].halfOpcode, undefined);
  });
});
