// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('BufferedStruct', () => {
  it('parses test properly', async () => {
    const { BufferedStruct } = await import('../compiled/BufferedStruct.js');
    const io = new KaitaiStream(fs.readFileSync('src/buffered_struct.bin'));
    const r = new BufferedStruct(io);
    assert.strictEqual(r.len1, 16);
    assert.strictEqual(r.block1.number1, 66);
    assert.strictEqual(r.block1.number2, 67);
    assert.strictEqual(r.len2, 8);
    assert.strictEqual(r.block2.number1, 68);
    assert.strictEqual(r.block2.number2, 69);
    assert.strictEqual(r.finisher, 238);
  });
});
