// Autogenerated from KST: please remove this line if doing any edits by hand!

import fs from 'node:fs';
import assert from 'node:assert/strict';
import { KaitaiStream } from 'kaitai-struct';

describe('EnumDeep', () => {
  it('parses test properly', async () => {
    const { EnumDeep } = await import('#testformats/EnumDeep.js');
    const io = new KaitaiStream(fs.readFileSync('src/enum_0.bin'));
    const r = new EnumDeep(io);
    assert.strictEqual(r.pet1, EnumDeep.Container1.Animal.CAT);
    assert.strictEqual(r.pet2, EnumDeep.Container1.Container2.Animal.HARE);
  });
});
